---
title: "prepare for Velocyto"
output: html_document
date: "2024-07-22"
---


```{r}
library(loomR)
```

# Load all files

```{r}
data_dirs <- list.files("RNA_velocity/",full.names = T)[grep("S0",list.files("RNA_velocity/",full.names = T))]
samples <- list.files("RNA_velocity/",full.names = F)[grep("S0",list.files("RNA_velocity/",full.names = F))]
```

```{r}
load("data/GBM_RNA_10_whole_V3.Robj")
```

# extract cluster label and embeddings

```{r}
whole_barcodes <- rownames(whole@meta.data)
umap_embeddings <- whole@reductions$umap@cell.embeddings
tsne_embeddings <- whole@reductions$tsne@cell.embeddings
```

```{r}
plotData <- cbind(whole@meta.data, whole_barcodes,umap_embeddings,tsne_embeddings)
```

```{r}
write.table(plotData,file = "data/plotData_whole_V3.tsv",sep = "\t",quote = F, col.names = T, row.names = F)
```

```{r}
PCA <- whole@reductions$pca@cell.embeddings
```

```{r}
write.table(PCA,file = "data/PCA_whole_V3.tsv",sep = "\t",quote = F, col.names = T, row.names = F)
```


