---
title: "Test Analysis Tools"
output: html_document
date: "2024-05-18"
---

# Overview

Tools tested includes SCENIC, WGCNA, and RNA velocity.All will be tested for the neoplastic subset

## RNA velocity: used Monocle 3 as alternative

```{r}
library(monocle3)
library(ggplot2)
library(dplyr)
library(Seurat)
library(SeuratWrappers)
```

```{r}
load("data/GBM_RNA_10_glioma_V2.Robj")
cds <- as.cell_data_set(Glioma)
```

```{r}
cds <- cluster_cells(cds, resolution=1e-3)
```

```{r}
plot_cells(cds, color_cells_by = "cluster", show_trajectory_graph = FALSE)
plot_cells(cds, color_cells_by = "partition", show_trajectory_graph = FALSE)

```

```{r}
cds <- learn_graph(cds, use_partition = T, verbose = FALSE)
```

```{r}
plot_cells(cds,
           color_cells_by = "cluster",
           label_groups_by_cluster=T,
           label_leaves=FALSE,
           label_branch_points=FALSE)
```

```{r}
cds <- order_cells(cds, root_cells = colnames(cds[,clusters(cds) == 4]))
plot_cells(cds,
           color_cells_by = "pseudotime",
           group_cells_by = "cluster",
           label_cell_groups = FALSE,
           label_groups_by_cluster=FALSE,
           label_leaves=F,
           label_branch_points=F,
           label_roots = T,
           trajectory_graph_color = "white")+theme_dark()
```
```{r}
Glioma <- AddMetaData(Glioma,metadata = cds@principal_graph_aux@listData$UMAP$pseudotime,col.name = "monocle3_trajectory")
```

```{r}
FeaturePlot(Glioma,features = "monocle3_trajectory")& scale_color_viridis_c() 
FeaturePlot(Glioma,features = "Mki67")
```
```{r}
DimPlot(Glioma,group.by = "orig.ident")
DimPlot(Glioma,group.by = "annotation_V1",split.by = "progress")
DimPlot(Glioma,group.by = "annotation_V1",split.by = "orig.ident")
```
```{r}
saveRDS(cds, file='data/glioma_monocle3.rds')
```

```{r}
save(Glioma,file = "data/GBM_RNA_10_glioma_V2.Robj")
```

## SCENIC: NO LONGER WORK in R

```{r}
if (!requireNamespace("BiocManager", quietly = TRUE)) install.packages("BiocManager")
BiocManager::version()
# If your bioconductor version is previous to 4.0, see the section bellow

## Required
BiocManager::install(c("AUCell", "RcisTarget"))
BiocManager::install(c("GENIE3")) # Optional. Can be replaced by GRNBoost

## Optional (but highly recommended):
# To score the network on cells (i.e. run AUCell):
BiocManager::install(c("zoo", "mixtools", "rbokeh"))
# For various visualizations and perform t-SNEs:
BiocManager::install(c("DT", "NMF", "ComplexHeatmap", "R2HTML", "Rtsne"))
# To support paralell execution (not available in Windows):
BiocManager::install(c("doMC", "doRNG"))
# To export/visualize in http://scope.aertslab.org
if (!requireNamespace("devtools", quietly = TRUE)) install.packages("devtools")
devtools::install_github("aertslab/SCopeLoomR", build_vignettes = TRUE)
devtools::install_github("aertslab/SCENIC") 
```


```{r}
suppressPackageStartupMessages({
  library(SCENIC)
  library(AUCell)
  library(RcisTarget)
  library(SCopeLoomR)
  library(KernSmooth)
  # library(BiocParallel)
  library(ggplot2)
  library(data.table)
  library(grid)
  library(ComplexHeatmap)
  library(Seurat)
})

```

```{r setwd, results='hide', warning=FALSE, eval=FALSE}
dir.create("SCENIC_OSU")
setwd("SCENIC_OSU") # Or `knitr::opts_knit$set(root.dir = 'example_results/SCENIC_MouseBrain')` in the first chunk if running a notebook
```

```{r load expression data}
load("data/GBM_RNA_10_glioma_V2.Robj")
```

```{r}
exprMat <- GetAssayData(Glioma,layer = "counts")
Idents(Glioma) <- Glioma$annotation_V1
cellInfo <- data.frame(CellType=Idents(Glioma))
```

```{r}
head(cellInfo)
cellInfo <- data.frame(cellInfo)
cbind(table(cellInfo$CellType))
dir.create("SCENIC_OSU/int")
saveRDS(cellInfo, file="SCENIC_OSU/int/cellInfo.Rds")
```
```{r}
colVars <- list(CellType=c("tumor_1"="forestgreen", 
                           "tumor_2"="darkorange", 
                           "tumor_3"="magenta4", 
                           "tumor_4"="hotpink", 
                           "tumor_5"="red3", 
                           "tumor_6"="skyblue", 
                           "tumor_7"="darkblue"))
colVars$CellType <- colVars$CellType[intersect(names(colVars$CellType), cellInfo$CellType)]
saveRDS(colVars, file="SCENIC_OSU/int/colVars.Rds")
plot.new(); legend(0,1, fill=colVars$CellType, legend=names(colVars$CellType))
```

```{r}
# dbFiles <- c("https://resources.aertslab.org/cistarget/databases/mus_musculus/mm9/refseq_r45/mc9nr/gene_based/mm9-500bp-upstream-7species.mc9nr.feather",
# "https://resources.aertslab.org/cistarget/databases/mus_musculus/mm9/refseq_r45/mc9nr/gene_based/mm9-tss-centered-10kb-7species.mc9nr.feather")
# mc9nr: Motif collection version 9: 24k motifs
dbpath <- "SCENIC_OSU/int/"
data(defaultDbNames)
dbs <- defaultDbNames[[org]]
#
```
Database files were manually downloaded to a specific directory and linked at the working directory. Problem encountered with initializing mm10 database; will migrate to python.

```{r}
org <- "mgi" # or hgnc, or dmel
dbDir <- "/Users/carisazeng/Desktop/WUSTL/SCENIC/" # RcisTarget databases location
myDatasetTitle <- "SCENIC on Glioma" # choose a name for your analysis
dbs <- "mm10_10kbp_up_10kbp_down_full_tx_v10_clust.genes_vs_motifs.rankings.feather"
data(list="motifAnnotations_mgi_v10", package="RcisTarget")
#motifAnnotations_mgi <- motifAnnotations_mgi_v10
scenicOptions <- initializeScenic(org=org, dbDir=dbDir, dbs=dbs, datasetTitle=myDatasetTitle, nCores=10) 

# Modify if needed
scenicOptions@inputDatasetInfo$cellInfo <- "SCENIC_OSU/int/cellInfo.Rds"
scenicOptions@inputDatasetInfo$colVars <- "SCENIC_OSU/int/colVars.Rds"
# Databases:
# scenicOptions@settings$dbs <- c("mm9-5kb-mc8nr"="mm9-tss-centered-5kb-10species.mc8nr.feather")
# scenicOptions@settings$db_mcVersion <- "v8"

# Save to use at a later time...
saveRDS(scenicOptions, file="SCENIC_OSU/int/scenicOptions.Rds") 
```


```{r}
vignetteFile <- "https://raw.githubusercontent.com/aertslab/SCENIC/master/vignettes/SCENIC_Running.Rmd"
download.file(vignetteFile, "SCENIC_myRun.Rmd")
```

