---
title: "Single Sample Processing and Merge"
output: html_document
---

```{r}
library(Seurat)
library(tidyverse)
library(harmony)
library(DoubletFinder)
library(miQC)
library(SoupX)
library(data.table)
library(SeuratWrappers) #For miQC
```

## Create Objects for each sample

```{r}
indir = "./alin_outs/" #Can be made into a command-line input
outdir = "./R_outs/"

```

```{r create object}
sample = "SR003099_NT-C"
NT_C <- CreateSeuratObject(Seurat::Read10X(paste(indir,"/", sample, "/outs/per_sample_outs/count/sample_filtered_feature_bc_matrix", sep = "")))
sample = "SR003099_NT-KO"
NT_KO <- CreateSeuratObject(Seurat::Read10X(paste(indir,"/", sample, "/outs/per_sample_outs/count/sample_filtered_feature_bc_matrix", sep = "")))
sample = "SR003099_T-C"
T_C <- CreateSeuratObject(Seurat::Read10X(paste(indir,"/", sample, "/outs/per_sample_outs/count/sample_filtered_feature_bc_matrix", sep = "")))
sample = "SR003099_T-KO"
T_KO <- CreateSeuratObject(Seurat::Read10X(paste(indir,"/", sample, "/outs/per_sample_outs/count/sample_filtered_feature_bc_matrix", sep = "")))
```

check initial cell number

```{r}
paste0("number of cells from NT-C is :", ncol(NT_C[["RNA"]]$counts))
paste0("number of genes from NT-C is :", nrow(NT_C[["RNA"]]$counts))
paste0("number of cells from NT-KO is :", ncol(NT_KO[["RNA"]]$counts))
paste0("number of genes from NT-KO is :", nrow(NT_KO[["RNA"]]$counts))
paste0("number of cells from T-C is :", ncol(T_C[["RNA"]]$counts))
paste0("number of genes from T-C is :", nrow(T_C[["RNA"]]$counts))
paste0("number of cells from T-KO is :", ncol(T_KO[["RNA"]]$counts))
paste0("number of genes from T-KO is :", nrow(T_KO[["RNA"]]$counts))
```

## Add additional metrics and perform FeatureScatter

```{r}
NT_C[["percent.mt"]] = PercentageFeatureSet(object = NT_C, pattern = "^MT-|^mt-")
NT_C$nFeature_RNA_log10 <- log10(NT_C$nFeature_RNA)
NT_C$nCount_RNA_log10 <- log10(NT_C$nCount_RNA)

NT_KO[["percent.mt"]] = PercentageFeatureSet(object = NT_KO, pattern = "^MT-|^mt-")
NT_KO$nFeature_RNA_log10 <- log10(NT_KO$nFeature_RNA)
NT_KO$nCount_RNA_log10 <- log10(NT_KO$nCount_RNA)

T_C[["percent.mt"]] = PercentageFeatureSet(object = T_C, pattern = "^MT-|^mt-")
T_C$nFeature_RNA_log10 <- log10(T_C$nFeature_RNA)
T_C$nCount_RNA_log10 <- log10(T_C$nCount_RNA)

T_KO[["percent.mt"]] = PercentageFeatureSet(object = T_KO, pattern = "^MT-|^mt-")
T_KO$nFeature_RNA_log10 <- log10(T_KO$nFeature_RNA)
T_KO$nCount_RNA_log10 <- log10(T_KO$nCount_RNA)
```


```{r}
FeatureScatter(NT_C, feature1 = "nFeature_RNA_log10", feature2 = "percent.mt")+
  ggtitle("NT-C")
FeatureScatter(NT_C, feature1 = "nFeature_RNA", feature2 = "percent.mt")+
  ggtitle("NT-C")
FeatureScatter(NT_KO, feature1 = "nFeature_RNA_log10", feature2 = "percent.mt")+
  ggtitle("NT-KO")
FeatureScatter(NT_KO, feature1 = "nFeature_RNA", feature2 = "percent.mt")+
  ggtitle("NT-KO")
FeatureScatter(T_C, feature1 = "nFeature_RNA_log10", feature2 = "percent.mt")+
  ggtitle("T-C")
FeatureScatter(T_C, feature1 = "nFeature_RNA", feature2 = "percent.mt")+
  ggtitle("T-C")
FeatureScatter(T_KO, feature1 = "nFeature_RNA_log10", feature2 = "percent.mt")+
  ggtitle("T-KO")
FeatureScatter(T_KO, feature1 = "nFeature_RNA", feature2 = "percent.mt")+
  ggtitle("T-KO")
```

## Run miQC for record keeping and checking threshold
Actual cutoff will be more conservative than miQC

### NT_C

```{r}
NT_C <- RunMiQC(NT_C, percent.mt = "percent.mt", nFeature_RNA = "nFeature_RNA", posterior.cutoff = 0.8,
               model.slot = "flexmix_model")
PlotMiQC(NT_C, color.by = "miQC.probability") + ggplot2::scale_color_gradient(low = "grey", high = "purple")+ggtitle("NT-C")
PlotMiQC(NT_C, color.by = "miQC.keep")+ggtitle("NT-C")
```
```{r}
table(NT_C$miQC.keep)
```


```{r}
Idents(NT_C) <- "NT-C"
VlnPlot(NT_C,features = c("percent.mt","nFeature_RNA_log10","nCount_RNA_log10"), split.by = "miQC.keep",split.plot = T, layer = "counts")
```

```{r}
miQC_kept <- subset(NT_C, miQC.keep == "keep")
VlnPlot(miQC_kept,features = c("percent.mt","nFeature_RNA_log10","nCount_RNA_log10"), split.by = "miQC.keep",split.plot = T, layer = "counts")
```

### NT_KO

```{r}
NT_KO <- RunMiQC(NT_KO, percent.mt = "percent.mt", nFeature_RNA = "nFeature_RNA", posterior.cutoff = 0.8,
               model.slot = "flexmix_model")
PlotMiQC(NT_KO, color.by = "miQC.probability") + ggplot2::scale_color_gradient(low = "grey", high = "purple")+ggtitle("NT-KO")
PlotMiQC(NT_KO, color.by = "miQC.keep")+ggtitle("NT-KO")
```
```{r}
table(NT_KO$miQC.keep)
```

```{r}
Idents(NT_KO) <- "NT-KO"
VlnPlot(NT_KO,features = c("percent.mt","nFeature_RNA_log10","nCount_RNA_log10"), split.by = "miQC.keep",split.plot = T, layer = "counts")
```

```{r}
miQC_kept <- subset(NT_KO, miQC.keep == "keep")
Idents(miQC_kept) <- "NT-KO: miQC_kept"
VlnPlot(miQC_kept,features = c("percent.mt","nFeature_RNA_log10","nCount_RNA_log10"), layer = "counts")
```

### T_C

```{r}
T_C <- RunMiQC(T_C, percent.mt = "percent.mt", nFeature_RNA = "nFeature_RNA", posterior.cutoff = 0.8,
               model.slot = "flexmix_model")
PlotMiQC(T_C, color.by = "miQC.probability") + ggplot2::scale_color_gradient(low = "grey", high = "purple")+ggtitle("T_C")
PlotMiQC(T_C, color.by = "miQC.keep")+ggtitle("T_C")
```

```{r}
table(T_C$miQC.keep)
```

```{r}
Idents(T_C) <- "T_C"
VlnPlot(T_C,features = c("percent.mt","nFeature_RNA_log10","nCount_RNA_log10"), split.by = "miQC.keep",split.plot = T, layer = "counts")
```

```{r}
miQC_kept <- subset(T_C, miQC.keep == "keep")
Idents(miQC_kept) <- "T_C: miQC_kept"
VlnPlot(miQC_kept,features = c("percent.mt","nFeature_RNA_log10","nCount_RNA_log10"), layer = "counts")
```

### T_KO

```{r}
T_KO <- RunMiQC(T_KO, percent.mt = "percent.mt", nFeature_RNA = "nFeature_RNA", posterior.cutoff = 0.8,
               model.slot = "flexmix_model")
PlotMiQC(T_KO, color.by = "miQC.probability") + ggplot2::scale_color_gradient(low = "grey", high = "purple")+ggtitle("T_KO")
PlotMiQC(T_KO, color.by = "miQC.keep")+ggtitle("T_KO")
```

```{r}
table(T_KO$miQC.keep)
```

```{r}
Idents(T_KO) <- "T_KO"
VlnPlot(T_KO,features = c("percent.mt","nFeature_RNA_log10","nCount_RNA_log10"), split.by = "miQC.keep",split.plot = T, layer = "counts")
```

```{r}
miQC_kept <- subset(T_KO, miQC.keep == "keep")
Idents(miQC_kept) <- "T_KO: miQC_kept"
VlnPlot(miQC_kept,features = c("percent.mt","nFeature_RNA_log10","nCount_RNA_log10"), layer = "counts")
```

## Trim cells by mt.percent first

### Try 5%

#### NT-C

```{r}
NT_C <- subset(NT_C, subset = percent.mt < 5)
paste0("The current number of cells from NT-C is :", ncol(NT_C[["RNA"]]$counts),". Was 2546")
VlnPlot(NT_C,features = c("percent.mt","nFeature_RNA_log10","nCount_RNA_log10"), split.by = "miQC.keep",split.plot = T, layer = "counts")
```

```{r}
VlnPlot(NT_C,features = c("percent.mt","nFeature_RNA_log10","nCount_RNA_log10"), layer = "counts")
```

#### NT-KO

```{r}
NT_KO <- subset(NT_KO, subset = percent.mt < 5)
paste0("The current number of cells from NT-KO is :", ncol(NT_KO[["RNA"]]$counts),". Was 3390")
VlnPlot(NT_KO,features = c("percent.mt","nFeature_RNA_log10","nCount_RNA_log10"), split.by = "miQC.keep",split.plot = T, layer = "counts")
VlnPlot(NT_KO,features = c("percent.mt","nFeature_RNA_log10","nCount_RNA_log10"), layer = "counts")
```
#### T-C


```{r}
T_C <- subset(T_C, subset = percent.mt < 5)
paste0("The current number of cells from T_C is :", ncol(T_C[["RNA"]]$counts),". Was 6919")
VlnPlot(T_C,features = c("percent.mt","nFeature_RNA_log10","nCount_RNA_log10"), split.by = "miQC.keep",split.plot = T, layer = "counts")
VlnPlot(T_C,features = c("percent.mt","nFeature_RNA_log10","nCount_RNA_log10"), layer = "counts")
```
#### T-KO


```{r}
T_KO <- subset(T_KO, subset = percent.mt < 5)
paste0("The current number of cells from T_C is :", ncol(T_KO[["RNA"]]$counts),". Was 8092")
VlnPlot(T_KO,features = c("percent.mt","nFeature_RNA_log10","nCount_RNA_log10"), split.by = "miQC.keep",split.plot = T, layer = "counts")
VlnPlot(T_KO,features = c("percent.mt","nFeature_RNA_log10","nCount_RNA_log10"), layer = "counts")
```

## Processing single sample 

### NT-C

```{r}
NT_C <- NormalizeData(object = NT_C, normalization.method = "LogNormalize", scale.factor = 10000)
NT_C <- FindVariableFeatures(object = NT_C, selection.method = 'mean.var.plot', mean.cutoff = c(0.0125, 5), dispersion.cutoff = c(0.5, Inf))
VariableFeatures(NT_C) <-  VariableFeatures(NT_C)[!grepl("^TRA|^TRB|^IGH|^IGK|MAMU-A", VariableFeatures(NT_C))]
VariableFeaturePlot(NT_C)
```

```{r}
NT_C <- ScaleData(object = NT_C, features = VariableFeatures(object = NT_C), vars.to.regress = c("nCount_RNA", "percent.mt"))
```

```{r}
NT_C <- RunPCA(NT_C,features =  VariableFeatures(object = NT_C))
NT_C <- RunUMAP(NT_C, dims = 1:10)
```

```{r}
FeaturePlot(NT_C,features = c("percent.mt","nFeature_RNA_log10"),reduction = "umap")
```


```{r}
FeaturePlot(NT_C,features = c("percent.mt","nCount_RNA_log10"),reduction = "umap")
```

```{r}
NT_C <- FindNeighbors(object = NT_C, dims = 1:10)              
NT_C <- FindClusters(object = NT_C, resolution = 0.1)
DimPlot(NT_C,reduction = "umap")
```
```{r eval=F}
save(NT_C, file = paste0(outdir,"NT_C.Robj"))
```

### NT-KO

```{r}
NT_KO <- NormalizeData(object = NT_KO, normalization.method = "LogNormalize", scale.factor = 10000)
NT_KO <- FindVariableFeatures(object = NT_KO, selection.method = 'mean.var.plot', mean.cutoff = c(0.0125, 5), dispersion.cutoff = c(0.5, Inf))
VariableFeatures(NT_KO) <-  VariableFeatures(NT_KO)[!grepl("^TRA|^TRB|^IGH|^IGK|MAMU-A", VariableFeatures(NT_KO))]
VariableFeaturePlot(NT_KO)
```

```{r}
NT_KO <- ScaleData(object = NT_KO, features = VariableFeatures(object = NT_KO), vars.to.regress = c("nCount_RNA", "percent.mt"))
```

```{r}
NT_KO <- RunPCA(NT_KO,features =  VariableFeatures(object = NT_KO))
NT_KO <- RunUMAP(NT_KO, dims = 1:10)
```

```{r}
FeaturePlot(NT_KO,features = c("percent.mt","nFeature_RNA_log10"),reduction = "umap")
```

```{r}
FeaturePlot(NT_KO,features = c("percent.mt","nCount_RNA_log10"),reduction = "umap")
```

```{r}
NT_KO <- FindNeighbors(object = NT_KO, dims = 1:10)              
NT_KO <- FindClusters(object = NT_KO, resolution = 0.1)
DimPlot(NT_KO,reduction = "umap")
```

```{r eval=F}
save(NT_KO, file = paste0(outdir,"NT_KO.Robj"))
```

### T-C

```{r}
T_C <- NormalizeData(object = T_C, normalization.method = "LogNormalize", scale.factor = 10000)
T_C <- FindVariableFeatures(object = T_C, selection.method = 'mean.var.plot', mean.cutoff = c(0.0125, 5), dispersion.cutoff = c(0.5, Inf))
VariableFeatures(T_C) <-  VariableFeatures(T_C)[!grepl("^TRA|^TRB|^IGH|^IGK|MAMU-A", VariableFeatures(T_C))]
VariableFeaturePlot(T_C)
```

```{r}
T_C <- ScaleData(object = T_C, features = VariableFeatures(object = T_C), vars.to.regress = c("nCount_RNA", "percent.mt"))
```

```{r}
T_C <- RunPCA(T_C,features =  VariableFeatures(object = T_C))
T_C <- RunUMAP(T_C, dims = 1:10)
```

```{r}
FeaturePlot(T_C,features = c("percent.mt","nFeature_RNA_log10"),reduction = "umap")
```

```{r}
FeaturePlot(T_C,features = c("percent.mt","nCount_RNA_log10"),reduction = "umap")
```

```{r}
T_C <- FindNeighbors(object = T_C, dims = 1:10)              
T_C <- FindClusters(object = T_C, resolution = 0.1)

```

```{r}
DimPlot(T_C,reduction = "umap")
```


```{r eval=F}
save(T_C, file = paste0(outdir,"T_C.Robj"))
```

### T-KO

```{r}
T_KO <- NormalizeData(object = T_KO, normalization.method = "LogNormalize", scale.factor = 10000)
T_KO <- FindVariableFeatures(object = T_KO, selection.method = 'mean.var.plot', mean.cutoff = c(0.0125, 5), dispersion.cutoff = c(0.5, Inf))
VariableFeatures(T_KO) <-  VariableFeatures(T_KO)[!grepl("^TRA|^TRB|^IGH|^IGK|MAMU-A", VariableFeatures(T_KO))]
VariableFeaturePlot(T_KO)
```

```{r}
T_KO <- ScaleData(object = T_KO, features = VariableFeatures(object = T_KO), vars.to.regress = c("nCount_RNA", "percent.mt"))
```

```{r}
T_KO <- RunPCA(T_KO,features =  VariableFeatures(object = T_KO))
T_KO <- RunUMAP(T_KO, dims = 1:10)
```


```{r}
FeaturePlot(T_KO,features = c("percent.mt","nFeature_RNA_log10"),reduction = "umap")
```

```{r}
FeaturePlot(T_KO,features = c("percent.mt","nCount_RNA_log10"),reduction = "umap")
```

```{r}
T_KO <- FindNeighbors(object = T_KO, dims = 1:10)              
T_KO <- FindClusters(object = T_KO, resolution = 0.1)
DimPlot(T_KO,reduction = "umap")
```

```{r eval=F}
save(T_KO, file = paste0(outdir,"T_KO.Robj"))
```

## merge

```{r}
whole <- merge(x=NT_C,y=c(NT_KO,T_C,T_KO),add.cell.ids=c("NT_C","NT_KO","T_C","T_KO"))
```


```{r }
NTC_range = range(grep("^NT_C",rownames(whole@meta.data)))

whole@meta.data$orig.ident[NTC_range[1]:NTC_range[2]] <- "NT_C"

NTKO_range = range(grep("^NT_KO",rownames(whole@meta.data)))

whole@meta.data$orig.ident[NTKO_range[1]:NTKO_range[2]] <- "NT_KO"

TC_range = range(grep("^T_C",rownames(whole@meta.data)))

whole@meta.data$orig.ident[TC_range[1]:TC_range[2]] <- "T_C"

TKO_range = range(grep("^T_KO",rownames(whole@meta.data)))

whole@meta.data$orig.ident[TKO_range[1]:TKO_range[2]] <- "T_KO"
```

```{r }
table(whole@meta.data$orig.ident)
```

```{r}
VlnPlot(whole,features = c("percent.mt","nFeature_RNA_log10","nCount_RNA_log10"),group.by = "orig.ident")
```


```{r eval=F}
save(whole,file = paste0(outdir,"whole.Robj"))
```

