---
title: "Expression Heatmap for Single Positive Cells"
output: html_document
date: "2024-03-25"
---

```{r}
library(Seurat) # youb know why
library(tidyverse) # base package for data organization and plotting
library(RColorBrewer) # for making palettes
library(gridExtra) # for arranging multiple plots
library(data.table) # well...
library(ComplexHeatmap)
library(circlize)
```

*temporarily load from V2p4 and subset; V3 is available on RIS*

```{r}
# define paths
indir <- "rds_V2/"
outdir <- "single_positive_heatmap/"
rds_pattern_list <- "" # in case needed for automation
dir.create(outdir)
```

```{r}
lymphoid_file <- "lymphoid_V2p4.Robj"
stromal_file <- "stromal_V2p4.Robj"
myeloid_file <- "myeloid_V2p4.Robj"
```

```{r}
gg_color_hue <- function(n) {
  hues = seq(15, 375, length = n + 1)
  hcl(h = hues, l = 65, c = 100)[1:n]
}
```


# Plot 1 - 3: Myeloid compartment(mono-mac, DC, Neutrophils)

```{r}
load(file = paste0(indir,myeloid_file))
```

```{r}
table(myeloid$hashtag) # sanity check
```

```{r}
myeloid <- subset(myeloid, subset = (hashtag == "Reporter-" )| (hashtag == "Reporter+" ))
```

```{r}
save(myeloid,file = paste0(indir,"myeloid_V2p4_SP.Robj"))
```

```{r}
table(myeloid$celltype)
```

## Plot 1: Mono-Mac

### SP

```{r}
mono_mac <- subset(myeloid, subset = celltype == "Mono/Mac")
```

```{r}
save(mono_mac,file = paste0(indir,"mono_mac_V2p4_SP.Robj"))
```


```{r}
avg_mono_mac <- AggregateExpression(mono_mac, assays = "RNA",features = c("Adgre1", "Cd14", "Ccr2", "Mertk","Tnf", "Fpr2", "Isg15", "Nos2", "Rsad2", "Spp1", "Il7r", "Ifitm3", "Ifit1", "Ifit3", "Il1b", "Slc2a1","Tgfb1", "Cd274", "Arg1", "Chil3", "Cx3cr1", "Mrc1","Trem2", "C1qa","Ccl2","Mki67"), return.seurat = T,group.by = c("annotation_V2","orig.ident","hashtag"))
```

```{r}
celltype_pal_mono <- gg_color_hue(6)
avg_mono_mac$sample <- rep(c(rep("Control",2),rep("ZBTB46",2)),6)
names(celltype_pal_mono) <- unique(unname(avg_mono_mac$annotation_V2))
col = list(
  Cell_type = celltype_pal_mono,
  Sample = c("Control"="black", "ZBTB46" = "red"),
  hashtag = c("Reporter-" = "lightgrey","Reporter+" = "red3")
)
ha <- HeatmapAnnotation(
   Cell_type = unname(avg_mono_mac$annotation_V2), Sample = unname(avg_mono_mac$sample),hashtag = unname(avg_mono_mac$hashtag),
  col = col
)
mat <-  GetAssayData(avg_mono_mac,layer = "scale.data")
Heatmap(mat,name = "Mono/Mac",top_annotation = ha,cluster_rows = T,cluster_columns = F,show_row_names = TRUE,show_column_names = F,row_names_side = "left",row_names_gp = grid::gpar(fontsize = 8),col = colorRamp2(c(-2,0,2),c("darkblue","white","red")))
```

```{r}
pdf(paste0(outdir,"Mono_mac_marker_Heatmap_SP.pdf"))
Heatmap(mat,name = "Mono/Mac",top_annotation = ha,cluster_rows = T,cluster_columns = F,show_row_names = TRUE,show_column_names = F,row_names_side = "left",row_names_gp = grid::gpar(fontsize = 8),col = colorRamp2(c(-2,0,2),c("darkblue","white","red")))
dev.off()
```

```{r}
save(avg_mono_mac,file = paste0(outdir,"avg_mono_mac.Robj"))
```

#### try log2FC

```{r}

```

```{r}
FeaturePlot(mono_mac,features = c("Itgae","Itgax"))
```



### RP only

```{r}
mono_mac_RP <- subset(mono_mac,subset = hashtag == "Reporter+" )
```


```{r}
avg_mono_mac_RP <- AggregateExpression(mono_mac_RP, assays = "RNA",features = c("Adgre1", "Cd14", "Ccr2", "Mertk","Tnf", "Fpr2", "Isg15", "Nos2", "Rsad2", "Spp1", "Il7r", "Ifitm3", "Ifit1", "Ifit3", "Il1b", "Slc2a1","Tgfb1", "Cd274", "Arg1", "Chil3", "Cx3cr1", "Mrc1","Trem2", "C1qa","Ccl2","Mki67"), return.seurat = T,group.by = c("annotation_V2","orig.ident"))
```
```{r}
save(avg_mono_mac_RP,file = paste0(outdir,"avg_mono_mac_RP.Robj"))
```

```{r}
celltype_pal_mono <- gg_color_hue(6)
avg_mono_mac_RP$sample <- rep(c(rep("Control",1),rep("ZBTB46",1)),6)
names(celltype_pal_mono) <- unique(unname(avg_mono_mac_RP$annotation_V2))
col = list(
  Cell_type = celltype_pal_mono,
  Sample = c("Control"="black", "ZBTB46" = "red")
)
ha <- HeatmapAnnotation(
   Cell_type = unname(avg_mono_mac_RP$annotation_V2), Sample = unname(avg_mono_mac_RP$sample),
  col = col
)
mat <-  GetAssayData(avg_mono_mac_RP,layer = "scale.data")
Heatmap(mat,name = "Mono/Mac",top_annotation = ha,cluster_rows = T,cluster_columns = F,show_row_names = TRUE,show_column_names = F,row_names_side = "left",row_names_gp = grid::gpar(fontsize = 8),col = colorRamp2(c(-2,0,2),c("darkblue","white","red")))
```

```{r}
pdf(paste0(outdir,"Mono_mac_marker_Heatmap_RP.pdf"))
Heatmap(mat,name = "Mono/Mac",top_annotation = ha,cluster_rows = T,cluster_columns = F,show_row_names = TRUE,show_column_names = F,row_names_side = "left",row_names_gp = grid::gpar(fontsize = 8),col = colorRamp2(c(-2,0,2),c("darkblue","white","red")))
dev.off()
```


## Plot 2: DC

### SP

```{r}
DC <- subset(myeloid, subset = celltype == "DC")
```

```{r}
table(DC$annotation)
table(DC$hashtag)
```

```{r}
DC_markers <- read.table("within_cell_type_DE/DC_annotation_markers.tsv",sep = "\t",header = T)
```

```{r}
DC_gene_selected <- DC_markers %>% group_by(cluster) %>% filter(p_val_adj < 0.05 & abs(avg_log2FC) > 1 & pct.1 > 0.5 ) %>% arrange(-abs(avg_log2FC)) %>% filter(!(grepl("^Gm",gene))) %>% slice_max(order_by = abs(avg_log2FC),n=10)
```

```{r}
DC_gene <- c(DC_gene_selected$gene,"Batf3","Zbtb46","Sirpa","H2-Ab1","Cd1a", "Cd1c","Cd1d1", "Cd8a", "Cd14", "Cd40", "Cd80", "Cd83", "Cd86", "Cd163", "Mrc1", "Cd207", "Cd209a", "Clec10a", "Notch2", "Cx3cr1", "Itgax", "Itgam", "Id2", "Klf4", "Irf4", "Irf7")
```

```{r}
avg_DC <- AggregateExpression(DC, assays = "RNA",features = DC_gene, return.seurat = T,group.by = c("annotation","orig.ident","hashtag"))
```

```{r}
DC_pal <- gg_color_hue(4)
avg_DC$sample <- c(rep(c(rep("Control",2),rep("ZBTB46",2)),3),rep("Control",2),"ZBTB46")
names(DC_pal) <- unique(unname(avg_DC$annotation))
col = list(
  Cell_type = DC_pal,
  Sample = c("Control"="black", "ZBTB46" = "red"),
  Hashtag = c("Reporter-" = "lightgrey","Reporter+" = "red3")
)
ha <- HeatmapAnnotation(
   Cell_type = unname(avg_DC$annotation), Sample = unname(avg_DC$sample),Hashtag = unname(avg_DC$hashtag),
  col = col
)
mat <-  GetAssayData(avg_DC,layer = "scale.data")
Heatmap(mat,name = "DC",top_annotation = ha,cluster_rows = T,cluster_columns = F,show_row_names = TRUE,show_column_names = F,row_names_side = "left",row_names_gp = grid::gpar(fontsize = 5),col = colorRamp2(c(-1.2,0,1.2),c("darkblue","white","red")))
```

```{r}
pdf(paste0(outdir,"DC_marker_Heatmap_SP.pdf"))
Heatmap(mat,name = "DC",top_annotation = ha,cluster_rows = T,cluster_columns = F,show_row_names = TRUE,show_column_names = F,row_names_side = "left",row_names_gp = grid::gpar(fontsize = 5),col = colorRamp2(c(-1.2,0,1.2),c("darkblue","white","red")))
dev.off()
```

```{r}
save(avg_DC,file = paste0(outdir,"avg_DC.Robj"))
```

### RP

```{r}
DC_RP <- subset(DC, subset = hashtag == "Reporter+")
```

```{r}
avg_DC_RP <- AggregateExpression(DC_RP, assays = "RNA",features = DC_gene, return.seurat = T,group.by = c("annotation","orig.ident"))
```

```{r}
DC_pal <- gg_color_hue(4)
avg_DC_RP$sample <- rep(c("Control","ZBTB46"),4)
names(DC_pal) <- unique(unname(avg_DC_RP$annotation))
col = list(
  Cell_type = DC_pal,
  Sample = c("Control"="black", "ZBTB46" = "red")
)
ha <- HeatmapAnnotation(
   Cell_type = unname(avg_DC_RP$annotation), Sample = unname(avg_DC_RP$sample),
  col = col
)
mat <-  GetAssayData(avg_DC_RP,layer = "scale.data")
Heatmap(mat,name = "DC",top_annotation = ha,cluster_rows = T,cluster_columns = F,show_row_names = TRUE,show_column_names = F,row_names_side = "left",row_names_gp = grid::gpar(fontsize = 5),col = colorRamp2(c(-1.2,0,1.2),c("darkblue","white","red")))
```

```{r}
pdf(paste0(outdir,"DC_marker_Heatmap_RP.pdf"))
Heatmap(mat,name = "DC",top_annotation = ha,cluster_rows = T,cluster_columns = F,show_row_names = TRUE,show_column_names = F,row_names_side = "left",row_names_gp = grid::gpar(fontsize = 5),col = colorRamp2(c(-1.2,0,1.2),c("darkblue","white","red")))
dev.off()
```

```{r}
save(avg_DC_RP,file = paste0(outdir,"avg_DC_RP.Robj"))
```


## Plot 3: neutrophil

```{r}
load(file = paste0(indir,"neutrophil_V2p4_sp.Robj"))
```

```{r}
table(neutrophil_sp$hashtag)
table(neutrophil_sp$annotation)
```
### SP

```{r}
avg_neu <- AggregateExpression(neutrophil_sp, assays = "RNA",features = c("Tnf","Icam1","Il1b","Cd14","Cd274","Il4ra","Tifa","Nfkbiz","F3","Cxcr4", "Arrb1","Tsc22d4", "Tsc22d3","Mmp9", "S100a8","Vegfa", "Mpo", "Osm"), return.seurat = T,group.by = c("annotation","orig.ident","hashtag"))

```

```{r}
neu_pal <- gg_color_hue(3)
avg_neu$sample <- rep(c(rep("Control",2),rep("ZBTB46",2)),3)
names(neu_pal) <- unique(unname(avg_neu$annotation))
col = list(
  Cell_type = neu_pal,
  Sample = c("Control"="black", "ZBTB46" = "red"),
  Hashtag = c("Reporter-" = "lightgrey","Reporter+" = "red3")
)
ha <- HeatmapAnnotation(
   Cell_type = unname(avg_neu$annotation), Sample = unname(avg_neu$sample),Hashtag = unname(avg_neu$hashtag),
  col = col
)
mat <-  GetAssayData(avg_neu,layer = "scale.data")
Heatmap(mat,name = "Neutrophil",top_annotation = ha,cluster_rows = T,cluster_columns = F,show_row_names = TRUE,show_column_names = F,row_names_side = "left",col = colorRamp2(c(-2,0,2),c("darkblue","white","red")))
```
```{r}
pdf(paste0(outdir,"Neutrophil_marker_Heatmap_SP.pdf"))
Heatmap(mat,name = "Neutrophil",top_annotation = ha,cluster_rows = T,cluster_columns = F,show_row_names = TRUE,show_column_names = F,row_names_side = "left",col = colorRamp2(c(-2,0,2),c("darkblue","white","red")))
dev.off()
```


```{r}
save(avg_neu,file = paste0(outdir,"avg_neutrophil.Robj"))
```

### RP

```{r}
neutrophil_RP <- subset(neutrophil_sp, subset = hashtag == "Reporter+")
```

```{r}
avg_neu_RP <- AggregateExpression(neutrophil_RP, assays = "RNA",features = c("Tnf","Icam1","Il1b","Cd14","Cd274","Il4ra","Tifa","Nfkbiz","F3","Cxcr4", "Arrb1","Tsc22d4", "Tsc22d3","Mmp9", "S100a8","Vegfa", "Mpo", "Osm"), return.seurat = T,group.by = c("annotation","orig.ident"))

```

```{r}
save(avg_neu_RP,file = paste0(outdir,"avg_neutrophil_RP.Robj"))
```

```{r}
neu_pal <- gg_color_hue(3)
avg_neu_RP$sample <- rep(c(rep("Control",1),rep("ZBTB46",1)),3)
names(neu_pal) <- unique(unname(avg_neu_RP$annotation))
col = list(
  Cell_type = neu_pal,
  Sample = c("Control"="black", "ZBTB46" = "red")
)
ha <- HeatmapAnnotation(
   Cell_type = unname(avg_neu_RP$annotation), Sample = unname(avg_neu_RP$sample),
  col = col
)
mat <-  GetAssayData(avg_neu_RP,layer = "scale.data")
Heatmap(mat,name = "Neutrophil",top_annotation = ha,cluster_rows = T,cluster_columns = F,show_row_names = TRUE,show_column_names = F,row_names_side = "left",col = colorRamp2(c(-2,0,2),c("darkblue","white","red")))
```

```{r}
pdf(paste0(outdir,"Neutrophil_marker_Heatmap_RP.pdf"))
Heatmap(mat,name = "Neutrophil",top_annotation = ha,cluster_rows = T,cluster_columns = F,show_row_names = TRUE,show_column_names = F,row_names_side = "left",col = colorRamp2(c(-2,0,2),c("darkblue","white","red")))
dev.off()
```

# Plot 4: stromal

## SP

```{r}
load(file = paste0(indir,stromal_file))
```

```{r}
table(stromal$hashtag) # sanity check
```

```{r}
stromal <- subset(stromal, subset = (hashtag == "Reporter-" )| (hashtag == "Reporter+" ))
```

```{r}
table(stromal$hashtag)
table(stromal$annotation_V2)
```

```{r}
save(stromal,file = paste0(indir,"stromal_V2p4_SP.Robj"))
```

```{r}
stromal_gene_list <- c("S100a4","Sparcl1","Vim","Sparcl1","Myh11","Mcam","Col5a2", "Aebp1", "Col1a1", "Col1a2", "Col3a1","Fap", "Mmp13", "Sfrp2","Rgs5","A2m", "Cpe", "Adamts1", "Acta2","Fabp7", "Vegfa", "Spp1", "Hilpda","S100a9", "S100a8", "Fcgr3", "G0s2","Nampt", "Rgs2", "Sod2","Il6","Has1","Clec3b","Islr","Ngfr","Tgfbr2","Cdh11","Itgbl1","Actn1","Lgals1","Tnfaip6","Ccn3","Gas1","Olfml3","Tpm1","Rbp1","Fhit","Opcml","Zeb1","Saa3","Myct1","Pecam1","Cyyr1","Kdr","Cdh5","H2-Ab1","Cd74","Cd80","Has1")
```

```{r}
stromal_avg <- AggregateExpression(stromal,assay = "RNA",features = stromal_gene_list,return.seurat = T,group.by = c("annotation_V2","orig.ident","hashtag"))
```


```{r}
save(stromal_avg,file = paste0(outdir,"avg_stromal.Robj"))
```

```{r}
stromal_pal <- gg_color_hue(6)
stromal_avg$sample <- c(rep("Control",2),rep("ZBTB46",1),
                        rep("Control",2),rep("ZBTB46",2),
                        rep("Control",2),rep("ZBTB46",2),
                        rep("Control",2),rep("ZBTB46",2),
                        rep("Control",2),rep("ZBTB46",2),
                        rep("Control",2),rep("ZBTB46",1))
names(stromal_pal) <- unique(unname(stromal_avg$annotation_V2))
col = list(
  Cell_type = stromal_pal,
  Sample = c("Control"="black", "ZBTB46" = "red"),
  Hashtag = c("Reporter-" = "lightgrey","Reporter+" = "red3")
)
ha <- HeatmapAnnotation(
   Cell_type = unname(stromal_avg$annotation_V2), 
   Sample = unname(stromal_avg$sample),
   Hashtag = unname(stromal_avg$hashtag),
  col = col
)
mat <-  GetAssayData(stromal_avg,layer = "scale.data")
Heatmap(mat,name = "stromal cells",top_annotation = ha,cluster_rows = T,cluster_columns = F,show_row_names = TRUE,show_column_names = F,row_names_gp = grid::gpar(fontsize = 5),row_names_side = "left",col = colorRamp2(c(-1.5,0,1.5),c("darkblue","white","red")))
```


```{r}
pdf(paste0(outdir,"Stromal_marker_Heatmap_SP.pdf"))
Heatmap(mat,name = "stromal cells",top_annotation = ha,cluster_rows = T,cluster_columns = F,show_row_names = TRUE,show_column_names = F,row_names_gp = grid::gpar(fontsize = 5),row_names_side = "left",col = colorRamp2(c(-1.5,0,1.5),c("darkblue","white","red")))
dev.off()
```

## SP

```{r}
stromal_RP <- subset(stromal, subset = (hashtag == "Reporter+" ))
```

```{r}
stromal_avg_RP <- AggregateExpression(stromal_RP,assay = "RNA",features = stromal_gene_list,return.seurat = T,group.by = c("annotation_V2","orig.ident"))
```

```{r}
save(stromal_avg_RP,file = paste0(outdir,"avg_stromal_RP.Robj"))
```

```{r}
stromal_pal <- gg_color_hue(6)
stromal_avg_RP$sample <- rep(c(rep("Control",1),rep("ZBTB46",1)),6)
names(stromal_pal) <- unique(unname(stromal_avg_RP$annotation_V2))
col = list(
  Cell_type = stromal_pal,
  Sample = c("Control"="black", "ZBTB46" = "red")
)
ha <- HeatmapAnnotation(
   Cell_type = unname(stromal_avg_RP$annotation_V2), 
   Sample = unname(stromal_avg_RP$sample),
  col = col
)
mat <-  GetAssayData(stromal_avg_RP,layer = "scale.data")
Heatmap(mat,name = "stromal cells",top_annotation = ha,cluster_rows = T,cluster_columns = F,show_row_names = TRUE,show_column_names = F,row_names_gp = grid::gpar(fontsize = 5),row_names_side = "left",col = colorRamp2(c(-1.5,0,1.5),c("darkblue","white","red")))
```

```{r}
pdf(paste0(outdir,"Stromal_marker_Heatmap_RP.pdf"))
Heatmap(mat,name = "stromal cells",top_annotation = ha,cluster_rows = T,cluster_columns = F,show_row_names = TRUE,show_column_names = F,row_names_gp = grid::gpar(fontsize = 5),row_names_side = "left",col = colorRamp2(c(-1.5,0,1.5),c("darkblue","white","red")))
dev.off()
```





# Plot 5: lymphoids

```{r}
load(file = paste0(indir,lymphoid_file))
```

```{r}
lymphoid_markers <- read.table(file = "expression_table_and_markers/lymphoid_annotation_markers.tsv",header = T,sep = "\t")
```

```{r}
table(lymphoid$hashtag) # sanity check
```

```{r}
lymphoid <- subset(lymphoid, subset = (hashtag == "Reporter-" )| (hashtag == "Reporter+" ))
```

```{r}
table(lymphoid$hashtag)
table(lymphoid$annotation)
```

```{r}
save(lymphoid,file = paste0(indir,"lymphoid_V2p4_sp.Robj"))
```

## picked markers
```{r}
avg_lymphoid <- AggregateExpression(lymphoid, assays = "RNA",features = c("Cd3e","Pdcd1","Havcr2","Isg15","Junb","Cebpb","Ccl3","Ccl5","Cd69","Gzma","Gzmb","Ncr1","Cd8a","Cd4","Foxp3","Mki67","Tigit","Tox","Ccr7","Tcf7","Lef1","Tbx21","Tyrobp","Klrb1c","Ctla4","Lag3","Eomes","Ifng","Xcl1","Cd7","Il2ra","Il7r","Sell","Entpd1", "Lag3", "Ctla4", "Icos", "Cd200", "Hspd1", "Klrc1", "Klrc2", "Cd44", "Havcr2", "Ifitm1", "Ifitm2", "Gzmb", "Gzmd", "Gzme", "Gzmg", "Klrg1", "Serpinb6a", "Serpinb9", "Il10", "Prf1", "Cxcr3", "Ccl5", "Foxo1", "Ncr1", "Sell", "Klra3", "Klra5", "Klra8", "Klra9"), return.seurat = T,group.by = c("annotation","orig.ident","hashtag"))
```

```{r}
save(avg_lymphoid,file = paste0(outdir,"avg_lymphoid_picked_marker.Robj"))
```

```{r}
lymph_pal <- gg_color_hue(11)
avg_lymphoid$sample <- c(rep("Control",2),rep("ZBTB46",1), # CD4
                        rep("Control",1),rep("ZBTB46",1), # CD8 Teff
                        rep("Control",2),rep("ZBTB46",2), # CD8 Tex
                        rep("Control",2),rep("ZBTB46",2), # CD8 Tnaive
                        rep("Control",1),rep("ZBTB46",1), # Ifn-responsive T 
                        rep("Control",2),rep("ZBTB46",2),# NK-1
                        rep("Control",2),rep("ZBTB46",2),# NK-2
                        rep("Control",2),rep("ZBTB46",2),# NK-3
                        rep("Control",2),rep("ZBTB46",1),# NK-4
                        rep("Control",2),rep("ZBTB46",1),# Prof NK
                        rep("Control",1),rep("ZBTB46",2) # Prof T
                        ) 

names(lymph_pal) <- unique(unname(avg_lymphoid$annotation))
col = list(
  Cell_type = lymph_pal,
  Sample = c("Control"="black", "ZBTB46" = "red"),
  Hashtag = c("Reporter-" = "lightgrey","Reporter+" = "red3")
)
ha <- HeatmapAnnotation(
   Cell_type = unname(avg_lymphoid$annotation), 
   Sample = unname(avg_lymphoid$sample),
   Hashtag = unname(avg_lymphoid$hashtag),
  col = col
)
mat <-  GetAssayData(avg_lymphoid,layer = "scale.data")
Heatmap(mat,name = "lymphoid cells",top_annotation = ha,cluster_rows = T,row_names_gp = grid::gpar(fontsize = 5),cluster_columns = F,show_row_names = TRUE,show_column_names = F,row_names_side = "left",col = colorRamp2(c(-2,0,2),c("darkblue","white","red")))
```
```{r}
pdf(paste0(outdir,"Lymphoid_picked_marker_Heatmap.pdf"))
Heatmap(mat,name = "lymphoid cells",top_annotation = ha,cluster_rows = T,row_names_gp = grid::gpar(fontsize = 5),cluster_columns = F,show_row_names = TRUE,show_column_names = F,row_names_side = "left",col = colorRamp2(c(-2,0,2),c("darkblue","white","red")))
dev.off()
```

## seurat markers


```{r}
lymphoid_markers_selected <- lymphoid_markers %>% group_by(cluster) %>% filter(p_val_adj < 0.05 & abs(avg_log2FC) > 1 & pct.1 > 0.2 ) %>% arrange(-abs(avg_log2FC)) %>% filter(!(grepl("^Gm",gene) | (grepl("*Rik$",gene)))) %>% slice_max(order_by = abs(avg_log2FC),n=20)
```


```{r}
avg_lymphoid <- AggregateExpression(lymphoid, assays = "RNA",features = unique(c(lymphoid_markers_selected$gene,"Entpd1", "Lag3", "Ctla4", "Icos", "Cd200", "Hspd1", "Klrc1", "Klrc2", "Cd44", "Havcr2", "Ifitm2", "Gzmb", "Klrg1", "Serpinb6a", "Serpinb9", "Cxcr3", "Ccl5", "Foxo1", "Ncr1", "Sell", "Klra3", "Klra5", "Klra9")), return.seurat = T,group.by = c("annotation","orig.ident","hashtag"))
```

```{r}
save(avg_lymphoid,file = paste0(outdir,"avg_lymphoid_seurat_marker.Robj"))
```


```{r}
lymph_pal <- gg_color_hue(11)
avg_lymphoid$sample <- c(rep("Control",2),rep("ZBTB46",1), # CD4
                        rep("Control",1),rep("ZBTB46",1), # CD8 Teff
                        rep("Control",2),rep("ZBTB46",2), # CD8 Tex
                        rep("Control",2),rep("ZBTB46",2), # CD8 Tnaive
                        rep("Control",1),rep("ZBTB46",1), # Ifn-responsive T 
                        rep("Control",2),rep("ZBTB46",2),# NK-1
                        rep("Control",2),rep("ZBTB46",2),# NK-2
                        rep("Control",2),rep("ZBTB46",2),# NK-3
                        rep("Control",2),rep("ZBTB46",1),# NK-4
                        rep("Control",2),rep("ZBTB46",1),# Prof NK
                        rep("Control",1),rep("ZBTB46",2) # Prof T
                        ) 

names(lymph_pal) <- unique(unname(avg_lymphoid$annotation))
col = list(
  Cell_type = lymph_pal,
  Sample = c("Control"="black", "ZBTB46" = "red"),
  Hashtag = c("Reporter-" = "lightgrey","Reporter+" = "red3")
)
ha <- HeatmapAnnotation(
   Cell_type = unname(avg_lymphoid$annotation), 
   Sample = unname(avg_lymphoid$sample),
   Hashtag = unname(avg_lymphoid$hashtag),
  col = col
)
mat <-  GetAssayData(avg_lymphoid,layer = "scale.data")
Heatmap(mat,name = "lymphoid cells",top_annotation = ha,cluster_rows = T,row_names_gp = grid::gpar(fontsize = 2),cluster_columns = F,show_row_names = TRUE,show_column_names = F,row_names_side = "left",col = colorRamp2(c(-2,0,2),c("darkblue","white","red")))
```

```{r}
pdf(paste0(outdir,"Lymphoid_marker_from_seurat_Heatmap.pdf"))
Heatmap(mat,name = "lymphoid cells",top_annotation = ha,cluster_rows = T,cluster_columns = F,show_row_names = TRUE,show_column_names = F,row_names_side = "left",row_names_gp = grid::gpar(fontsize = 2),col = colorRamp2(c(-2,0,2),c("darkblue","white","red")))
dev.off()
```

