---
title: "0-2_second_round_QC"
output: html_document
date: "2024-10-15"
---

**Forget about 0-1-5. DoubletFinder is not working well here.**


```{r}
# define packages
library(Seurat)
library(tidyverse)
library(harmony)

library(miQC)
library(SeuratWrappers) # for miQC
library(scuttle)
```

```{r}
library(RColorBrewer)
pal <- c(brewer.pal(n = 12,name = "Set3"),brewer.pal(n = 12,name = "Paired"),brewer.pal(n = 8,name = "Accent"))
pal[2] <- "darkred"
pal[9] <- "grey25"
pal[23] <- "turquoise4"
pal[19] <- colors()[60]
pal[13] <- "darkblue"
pal[28] <- colors()[16]
pal[31] <- colors()[54] 
pal <- c(pal,colors()[c(85,84,83,89,45,31,41,42,26,29,10,139,107,108,120,109,119,121,143)])
```

```{r}
indir <- "RDS/"
RDSdir <- "RDS/"
outdir_prop <- "proportion_plots/"
if (!dir.exists(outdir_prop)) dir.create(outdir_prop)

```

```{r}
load(paste0(indir,"whole_V1p2.Robj"))
```

Clusters were discussed using res=0.8 during the meeting.
c9 is non-glial cells, c8 is possibly BAM, and c7 is a low transcript level artifact.

```{r}
DimPlot(whole, group.by = "RNA_snn_res.0.8",label = T) +scale_color_manual(values = pal)
```

```{r}
Idents(whole) <- "RNA_snn_res.0.8"
whole <- subset(whole, idents = c(0:10)[!(c(0:10) %in% c(7,8,9))])

```

```{r}
DimPlot(whole, group.by = "RNA_snn_res.0.8",label = T) +scale_color_manual(values = pal[!(c(1:11) %in% c(8,9,10))])
```

```{r eval=FALSE}
save(whole, file = paste0(RDSdir,"whole_V1p4.Robj"))
```

```{r}
load(paste0(indir,"whole_V1p4.Robj"))
```

```{r}
DimPlot(whole, group.by = "RNA_snn_res.0.8",label = T) +scale_color_manual(values = pal[!(c(1:11) %in% c(8,9,10))])
```


```{r}
whole <- FindVariableFeatures(object = whole, selection.method = 'mean.var.plot', mean.cutoff = c(0.0125, 5), dispersion.cutoff = c(0.5, Inf))
#VariableFeatures(whole) <-  VariableFeatures(whole) [!grepl("^Tra|^Trb|^Igh|^Igk|Mamu-a", VariableFeatures(whole))]
VariableFeaturePlot(whole)

whole <- ScaleData(object = whole, features = VariableFeatures(object = whole), vars.to.regress = c("nCount_RNA"))
whole <- RunPCA(object = whole,
                features =  VariableFeatures(object = whole),
                dims = 1:50)
gc()
ElbowPlot(whole,ndims = 50)
```

```{r message=FALSE}
whole <- RunHarmony(object = whole, group.by.vars = c("orig.ident"), max.iter.harmony = 20) # use harmony to correct for batch effect
whole <- RunUMAP(whole,dims = 1:20,reduction = "harmony") # use harmony embedding for downstream analysis
whole <- RunTSNE(whole,dims = 1:20,reduction = "harmony")

whole <- FindNeighbors(whole, dims = 1:20,reduction = "harmony")
for(res in seq(0.1, 1, 0.1))  {   # iterate over a range of resolutions
  whole <- FindClusters(object = whole, resolution = res, print.output = 0, save.SNN = TRUE)
} 
gc()
whole <- JoinLayers(whole) # required for seurat V5
```
```{r}
DimPlot(whole, group.by = "RNA_snn_res.0.1",label = T) +scale_color_manual(values = pal)
DimPlot(whole, group.by = "RNA_snn_res.0.7",label = T) +scale_color_manual(values = pal)
```

```{r}
FeaturePlot(whole,features = "Gpnmb")
FeaturePlot(whole,features = "Axl")
FeaturePlot(whole,features = "Itgax")
FeaturePlot(whole,features = "Ifit3")
FeaturePlot(whole,features = "Stat1")
FeaturePlot(whole,features = "P2ry12")
```


```{r eval=FALSE}
save(whole, file = paste0(RDSdir,"whole_V1p4.Robj"))
```

```{r}
DimPlot(whole, group.by = "orig.ident", split.by = "orig.ident")
```

```{r}
whole@meta.data <- whole@meta.data %>% mutate(
  condition = case_match(
    orig.ident,
    "PS19_Oil" ~ "PS19",
    "PS19_TAM" ~ "PS19",
    "WT_Oil" ~ "WT",
    "WT_TAM" ~ "WT"
  ),
  treatment = case_match(
    orig.ident,
    "PS19_Oil" ~ "Oil",
    "PS19_TAM" ~ "TAM",
    "WT_Oil" ~ "Oil",
    "WT_TAM" ~ "TAM"
  )
) %>% mutate(
  condition = factor(condition, levels = c("WT", "PS19")),
  treatment = factor(treatment, levels = c("Oil", "TAM")),
  orig.ident = factor(orig.ident, levels = c("WT_Oil", "WT_TAM", "PS19_Oil","PS19_TAM"))
)
```


```{r}
save(whole, file = paste0(RDSdir,"whole_V1p4.Robj"))
```

```{r}
prop_table <- whole@meta.data %>% group_by(orig.ident,RNA_snn_res.0.7) %>% summarise(cluster_size = n()) %>% ungroup() %>% group_by(orig.ident) %>% mutate(proportion = cluster_size/sum(cluster_size))
```

```{r}
p1 <- ggplot(prop_table)+
  geom_bar(aes(x = orig.ident, y = proportion, fill = RNA_snn_res.0.7),stat = "identity", position = "dodge")+
  facet_wrap(~RNA_snn_res.0.7, scales = "free")+
  scale_fill_manual(values = pal)+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90))
p2 <- DimPlot(whole, group.by = "RNA_snn_res.0.7",label = T,pt.size = 1,label.box = T) +scale_color_manual(values = pal[c(1:8,10:12,14)])+scale_fill_manual(values = pal[c(1:8,10:12,14)])
g <- gridExtra::grid.arrange(grobs = list(p1,p2),ncol = 2)
ggsave(plot = g, filename = paste0(outdir_prop,"whole_V1p4_res07_proportion_plot.pdf"),width = 15, height = 8)
```



