---
title: "0-4_TAM_vs_Oil_in_PS19"
output: html_document
date: "2024-10-16"
---

```{r}
# define packages
library(Seurat)
library(tidyverse)
library(harmony)
library(MAST)

library(miQC)
library(SeuratWrappers) # for miQC
library(scuttle)

library(msigdbr)
library(fgsea)
library(org.Mm.eg.db)
library(data.table) # well...
```

```{r}
library(RColorBrewer)
pal <- c(brewer.pal(n = 12,name = "Set3"),brewer.pal(n = 12,name = "Paired"),brewer.pal(n = 8,name = "Accent"))
pal[2] <- "darkred"
pal[9] <- "grey25"
pal[23] <- "turquoise4"
pal[19] <- colors()[60]
pal[13] <- "darkblue"
pal[28] <- colors()[16]
pal[31] <- colors()[54] 
pal <- c(pal,colors()[c(85,84,83,89,45,31,41,42,26,29,10,139,107,108,120,109,119,121,143)])
```

```{r}
indir <- "RDS/"
RDSdir <- "RDS/"
outdir_DE <- "TAM_vs_Oil_DE/"
if (!dir.exists(outdir_DE)) dir.create(outdir_DE)
```

## Prepare

```{r}
load(paste0(indir,"whole_V1p4.Robj"))
```

```{r}
DimPlot(whole,group.by = "condition")
```
Extract PS19 subset


```{r}
PS19 <- subset(whole, subset = condition == "PS19")
```

```{r}
DimPlot(PS19,group.by = "RNA_snn_res.0.7")
```

```{r}
Idents(object = PS19) <- ("RNA_snn_res.0.7")
cell.num <- table(PS19@meta.data$RNA_snn_res.0.7)
ClusterLabels = paste(names(cell.num), paste0("(n = ", cell.num, ")"))
ClusterBreaks = names(cell.num)

DimPlot(object = PS19,label = TRUE, label.size = 5, reduction = "umap") +
  scale_colour_manual(values = pal[1:12], 
                        labels = ClusterLabels) +
  labs(x = "UMAP 1",
       y = "UMAP 2")


```

```{r}
cluster_prop <- PS19@meta.data %>% group_by(RNA_snn_res.0.7,treatment) %>% summarise(size = n()) %>% ungroup() %>%
  group_by(treatment) %>% mutate(percentage = 100*size/sum(size))
```

```{r}
ggplot(cluster_prop)+
  geom_bar(aes(x = treatment,y = percentage, fill = RNA_snn_res.0.7),stat = "identity", position = "dodge")+
  geom_text(aes(x = treatment,y = percentage,label = size),vjust = 1 ,color = "white",size = 3)+
  facet_wrap(~RNA_snn_res.0.7,scales = "free")+scale_fill_manual(values = pal[c(1:8,10,13:14,16)])+theme_dark()
```

remove clusters with <50 cells in either cluster (essentially remove 2,8,9,10,11) --> remove clusters with <80 cells.


```{r}
p1 <- DimPlot(object = PS19,label = TRUE, label.size = 5, reduction = "umap") +
  scale_colour_manual(values = pal[c(1:8,10,13:14,16)], 
                        labels = ClusterLabels) +
  labs(x = "UMAP 1",
       y = "UMAP 2")
p2 <- ggplot(cluster_prop)+
  geom_bar(aes(x = treatment,y = percentage, fill = RNA_snn_res.0.7),stat = "identity", position = "dodge")+
  geom_text(aes(x = treatment,y = percentage,label = size),vjust = 1 ,color = "white",size = 3)+
  facet_wrap(~RNA_snn_res.0.7,scales = "free")+scale_fill_manual(values = pal[c(1:8,10,13:14,16)])+theme_dark()
g <- gridExtra::grid.arrange(grobs = list(p1,p2),ncol = 2)

ggsave(paste0("proportion_plots/PS19_cluster_prop_V1p4_res07.pdf"), plot = g, width = 12, height = 5)
```

```{r}
save(PS19, file = paste0(RDSdir,"PS19_all_V1p4.Rdata"))
```


```{r}
Idents(PS19) <- "RNA_snn_res.0.7"

PS19 <- subset(PS19, idents = c(0:1,3:7))
```

```{r}
save(PS19, file = paste0(RDSdir,"PS19_for_DE_V1p4.Rdata"))
```

## DE

```{r}
de_clusters <- function(current_cluster) {
  groups <- gsub(" ","_",paste0(conditions,"_",current_cluster))
  both_markers <- FindMarkers(PS19, ident.1=groups[1], ident.2=groups[2], test.use="MAST", min.pct=0.00, logfc.threshold = 0) # change name of object 
  marker_genes <- row.names(both_markers)
  mutate(both_markers, gene = marker_genes, cluster = current_cluster)
}
```


```{r}
load(paste0(RDSdir,"PS19_for_DE_V1p4.Rdata"))
```


```{r}
PS19$group <- gsub(" ","_",paste0(PS19$treatment,"_",PS19$RNA_snn_res.0.7))
conditions <- rev(unique(PS19$treatment)[order(unique(PS19$treatment))])
clusters <- unique(PS19$RNA_snn_res.0.7)
plts <- list()
padj_thres = 10e-2
log2FC_thres = 1
Idents(PS19) <- PS19$group
```



```{r}
table(PS19$group)
```

```{r}
conditions[1] # make it TAM v.s. Oil
```

```{r}
for (i in clusters) {
  output_file <- paste0(outdir_DE,paste0("PS19_V1p4_res07_",conditions[1],'_vs_',conditions[2],'_', i, '.tsv'))
  output_file_flt <- paste0(outdir_DE,paste0("PS19_V1p4_res07_",conditions[1],'_vs_',conditions[2],'_', i, '_filtered.tsv'))
  de_results_tbl <- lapply(i, de_clusters) 
  de_results_tbl <- de_results_tbl %>% bind_rows() %>%
			arrange(desc(abs(avg_log2FC))) %>%
			mutate(threshold = case_when(
			(p_val_adj < padj_thres) & (abs(avg_log2FC) > log2FC_thres) ~ "Pass",
			.default = "Fail"
			))
  write.table(de_results_tbl, output_file,sep="\t",row.names=F)
  
  
  de_results_tbl <- de_results_tbl %>% 
			filter(p_val_adj < padj_thres) %>%
			filter(abs(avg_log2FC) > log2FC_thres)
			
  write.table(de_results_tbl, output_file_flt,sep="\t",row.names=F)
}

 
```

make volcano plots

```{r}
for (i in clusters) {
  DE <- read.table(paste0(outdir_DE,paste0("PS19_V1p4_res07_",conditions[1],'_vs_',conditions[2],'_', i, '.tsv')))
  top15genes <- DE %>% filter(p_val_adj < padj_thres & abs(avg_log2FC) > log2FC_thres) %>% slice_max(order_by = abs(avg_log2FC)*(-log10(p_val_adj)),n = 15)
  
 
  g <- ggplot(DE,aes(x = avg_log2FC, y = -log10(p_val_adj), color = threshold))+
  geom_point()+
  ggrepel::geom_label_repel(aes(label=ifelse(gene %in% top15genes$gene,as.character(gene),'')),
                  size = 2,
                  segment.color = 'grey50',
                  max.overlaps = 30) +
  geom_hline(yintercept = c(1),color = "red2")+
  geom_vline(xintercept = c(-1,1),color = "red2")+
  ggtitle(paste0("Cluster ", i, " Volcano Plot: ", conditions[1]," vs ",conditions[2]))+ylab("-log10 padj")+theme_classic()

  ggsave(filename = paste0(outdir_DE,paste0("PS19_V1p4_res07_",conditions[1],'_vs_',conditions[2],'_', i, '_volcano.pdf')), plot = g ,width = 10, height = 12 )
}

 
```

Consider Bulk DE

```{r}
load(paste0(RDSdir,"PS19_all_V1p4.Rdata"))
```


```{r}
PS19$group <- gsub(" ","_",paste0(PS19$treatment))
conditions <- rev(unique(PS19$treatment)[order(unique(PS19$treatment))])
plts <- list()
padj_thres = 10e-2
log2FC_thres = 1
Idents(PS19) <- PS19$group
```

```{r}
table(PS19$group)
table(PS19$condition)
```

```{r}

output_file <- paste0(outdir_DE,paste0("PS19_V1p4_res07_",conditions[1],'_vs_',conditions[2] , '.tsv'))
output_file_flt <- paste0(outdir_DE,paste0("PS19_V1p4_res07_",conditions[1],'_vs_',conditions[2], '_filtered.tsv'))
  

groups <- gsub(" ","_",paste0(conditions))
de_results_tbl <- FindMarkers(PS19, ident.1=groups[1], ident.2=groups[2], test.use="MAST", min.pct=0.00, logfc.threshold = 0) # change name of object 
marker_genes <- row.names(de_results_tbl)
de_results_tbl <- mutate(de_results_tbl, gene = marker_genes)

de_results_tbl <- de_results_tbl %>% bind_rows() %>%
			arrange(desc(abs(avg_log2FC))) %>%
			mutate(threshold = case_when(
			(p_val_adj < padj_thres) & (abs(avg_log2FC) > log2FC_thres) ~ "Pass",
			.default = "Fail"
			))
write.table(de_results_tbl, output_file,sep="\t",row.names=T)
  
  
de_results_tbl <- de_results_tbl %>% 
			filter(p_val_adj < padj_thres) %>%
			filter(abs(avg_log2FC) > log2FC_thres)
			
write.table(de_results_tbl, output_file_flt,sep="\t",row.names=T)

```

```{r}
DE <- read.table(paste0(outdir_DE,paste0("PS19_V1p4_res07_",conditions[1],'_vs_',conditions[2],'.tsv')))
  top15genes <- DE %>% filter(p_val_adj < padj_thres & abs(avg_log2FC) > log2FC_thres) %>% slice_max(order_by = abs(avg_log2FC)*(-log10(p_val_adj)),n = 15)
  
 
  g <- ggplot(DE,aes(x = avg_log2FC, y = -log10(p_val_adj), color = threshold))+
  geom_point()+
  ggrepel::geom_label_repel(aes(label=ifelse(gene %in% top15genes$gene,as.character(gene),'')),
                  size = 2,
                  segment.color = 'grey50',
                  max.overlaps = 30) +
  geom_hline(yintercept = c(1),color = "red2")+
  geom_vline(xintercept = c(-1,1),color = "red2")+
  ggtitle(paste0("Volcano Plot: ", conditions[1]," vs ",conditions[2]))+ylab("-log10 padj")+theme_classic()

  ggsave(filename = paste0(outdir_DE,paste0("PS19_V1p4_res07_",conditions[1],'_vs_',conditions[2], '_volcano.pdf')), plot = g ,width = 10, height = 12 )
```

```{r}
write.table(DE, paste0(outdir_DE,paste0("PS19_V1p4_res07_",conditions[1],'_vs_',conditions[2] , '.tsv')),sep="\t",row.names=F)
de_results_tbl <- DE %>% 
			filter(p_val_adj < padj_thres) %>%
			filter(abs(avg_log2FC) > log2FC_thres)
write.table(de_results_tbl, paste0(outdir_DE,paste0("PS19_V1p4_res07_",conditions[1],'_vs_',conditions[2], '_filtered.tsv')),sep="\t",row.names=F)

```


## GSEA on bulk

```{r}
H_df<- msigdbr(species = "Mus musculus", category = "H")
# Imm_df <- msigdbr(species = "Mus musculus", category = "C7",subcategory = "IMMUNESIGDB")
# Celltype_df <- msigdbr(species = "Mus musculus", category = "C8")
C2_KEGG <- msigdbr(species = "Mus musculus", category = "C2",subcategory = "CP:KEGG")
C2_React <- msigdbr(species = "Mus musculus", category = "C2",subcategory = "CP:REACTOME")
#CP_df <- msigdbr(species = "Mus musculus", category = "C2",subcategory = "CP")
GO_BP_df <- msigdbr(species = "Mus musculus", category = "C5",subcategory = "GO:BP")
GO_CC_df <- msigdbr(species = "Mus musculus", category = "C5",subcategory = "GO:CC")
GO_MF_df <- msigdbr(species = "Mus musculus", category = "C5",subcategory = "GO:MF")



fgsea_sets_Hallmark <- H_df %>% split(x = .$gene_symbol, f = .$gs_name)
# fgsea_sets_Imm <- Imm_df %>% split(x = .$gene_symbol, f = .$gs_name)
fgsea_sets_KEGG <- C2_KEGG %>% split(x = .$gene_symbol, f = .$gs_name)
fgsea_sets_REACT <- C2_React %>% split(x = .$gene_symbol, f = .$gs_name)
#fgsea_sets_CP <- CP_df %>% split(x = .$gene_symbol, f = .$gs_name)
fgsea_sets_GOBP <- GO_BP_df %>% split(x = .$gene_symbol, f = .$gs_name)
fgsea_sets_GOCC <- GO_CC_df %>% split(x = .$gene_symbol, f = .$gs_name)
fgsea_sets_GOMF <- GO_MF_df %>% split(x = .$gene_symbol, f = .$gs_name)
# fgsea_sets_Celltype <- Celltype_df %>% split(x = .$gene_symbol, f = .$gs_name)
```


```{r for bulk}
fgsea_res <- function(cell_type_vector, DE_genes, choose_n = 100, choose_tops = F,gene_set = fgsea_sets_Hallmark,mode = "combined",outdir){
  if(!dir.exists(outdir)) {dir.create(outdir)}
  fgsea_res <- list()
  DE_selected <- DE_genes %>% mutate(metric = sign(avg_log2FC)*(-log10(p_val_adj))) %>% filter(!is.infinite(metric))
  if (mode == "simple"){
    DE_selected <- DE_genes %>% mutate(metric = avg_log2FC) %>% filter(!is.infinite(metric))
  }
  for (i in cell_type_vector) {
    DE <- DE_selected %>% arrange(desc(metric)) %>% dplyr::select(gene,metric)
    if (choose_tops){
      DE_top <- DE %>% group_by(cluster) %>% slice_max(order_by = metric, n = choose_n)
      DE_tail <- DE %>% group_by(cluster) %>% slice_min(order_by = metric, n = choose_n)
      DE <- rbind(DE_top,DE_tail)
    }
    DE <- DE %>% arrange(desc(metric)) %>% dplyr::select(gene,metric)
    rankings <- DE$metric
    names(rankings) <- DE$gene

    plot(rankings)
    title(main = i)
    fgseaRes <- fgsea(gene_set, stats = rankings,nPermSimple = 10000)
    fgseaResTidy <- fgseaRes %>%
      as_tibble() %>% filter(padj < 0.05 ) %>%
      arrange(desc(NES))
  fgsea_res[[i]] <- fgseaResTidy
  fwrite(fgseaResTidy, file=paste0(outdir,i,"_fgsea.tsv"), sep="\t", sep2=c("", " ", ""))
  } # need to add name of gene sets to the file name
   return(fgsea_res)
}
```


```{r}
DE <- read.table(paste0(outdir_DE,paste0("PS19_V1p4_res07_",conditions[1],'_vs_',conditions[2],'.tsv')))
fgsea_res(paste0("PS19_V1p4_res07_",conditions[1],'_vs_',conditions[2]), DE,gene_set = fgsea_sets_Hallmark,mode = "simple",outdir = paste0(outdir_DE,"/GSEA_Hallmark/"))

fgsea_res(paste0("PS19_V1p4_res07_",conditions[1],'_vs_',conditions[2]), DE,gene_set = fgsea_sets_KEGG,mode = "simple",outdir = paste0(outdir_DE,"/GSEA_KEGG/"))
fgsea_res(paste0("PS19_V1p4_res07_",conditions[1],'_vs_',conditions[2]), DE,gene_set = fgsea_sets_REACT,mode = "simple",outdir = paste0(outdir_DE,"/GSEA_REACTOME/"))

fgsea_res(paste0("PS19_V1p4_res07_",conditions[1],'_vs_',conditions[2]), DE,gene_set = fgsea_sets_GOBP,mode = "simple",outdir = paste0(outdir_DE,"/GSEA_GO_BP/"))
fgsea_res(paste0("PS19_V1p4_res07_",conditions[1],'_vs_',conditions[2]), DE,gene_set = fgsea_sets_GOCC,mode = "simple",outdir = paste0(outdir_DE,"/GSEA_GO_CC/"))
fgsea_res(paste0("PS19_V1p4_res07_",conditions[1],'_vs_',conditions[2]), DE,gene_set = fgsea_sets_GOMF,mode = "simple",outdir = paste0(outdir_DE,"/GSEA_GO_MF/"))
```
## GSEA on clusters

```{r}
fgsea_res <- function(cell_type_vector, DE_genes, choose_n = 100, choose_tops = F,gene_set = fgsea_sets_Hallmark,mode = "combined",outdir){
  if(!dir.exists(outdir)) {dir.create(outdir)}
  fgsea_res <- list()
  #DE_selected <- DE_genes %>% group_by(cluster) %>% filter(p_val_adj < 0.05 & abs(avg_log2FC) > 1 & pct.1 > 0.1) %>% mutate(metric = sign(avg_log2FC)*(-log10(p_val_adj))) %>% filter(!is.infinite(metric))
  DE_selected <- DE_genes %>% mutate(metric = sign(avg_log2FC)*(-log10(p_val_adj))) %>% filter(!is.infinite(metric))
  if (mode == "simple"){
    DE_selected <- DE_genes %>% mutate(metric = avg_log2FC) %>% filter(!is.infinite(metric))
  }
  for (i in cell_type_vector) {
    DE <- DE_selected[DE_selected$cluster == i,] %>% arrange(desc(metric)) %>% dplyr::select(gene,metric)
    if (choose_tops){
      DE_top <- DE %>% group_by(cluster) %>% slice_max(order_by = metric, n = choose_n)
      DE_tail <- DE %>% group_by(cluster) %>% slice_min(order_by = metric, n = choose_n)
      DE <- rbind(DE_top,DE_tail)
    }
    DE <- DE %>% arrange(desc(metric)) %>% dplyr::select(gene,metric)
    rankings <- DE$metric
    names(rankings) <- DE$gene
    #print(rankings)
    plot(rankings)
    title(main = i)
    fgseaRes <- fgsea(gene_set, stats = rankings,nPermSimple = 10000)
    fgseaResTidy <- fgseaRes %>%
      as_tibble() %>% filter(padj < 0.05 ) %>%
      arrange(desc(NES))
  fgsea_res[[i]] <- fgseaResTidy
  fwrite(fgseaResTidy, file=paste0(outdir,i,"_fgsea.tsv"), sep="\t", sep2=c("", " ", ""))
  } # need to add name of gene sets to the file name
   return(fgsea_res)
}
```


```{r}
PS19$group <- gsub(" ","_",paste0(PS19$treatment,"_",PS19$RNA_snn_res.0.7))
conditions <- rev(unique(PS19$treatment)[order(unique(PS19$treatment))])
clusters <- unique(PS19$RNA_snn_res.0.7)
plts <- list()
padj_thres = 10e-2
log2FC_thres = 1
Idents(PS19) <- PS19$group
```




