---
title: "0-5_check_driver_of_variance"
output: html_document
date: "2024-10-24"
---

```{r}
# define packages
library(Seurat)
library(tidyverse)
library(harmony)
library(MAST)

library(miQC)
library(SeuratWrappers) # for miQC
library(scuttle)

library(msigdbr)
library(fgsea)
library(org.Mm.eg.db)
library(data.table) # well...
```

```{r}
library(RColorBrewer)
pal <- c(brewer.pal(n = 12,name = "Set3"),brewer.pal(n = 12,name = "Paired"),brewer.pal(n = 8,name = "Accent"))
pal[2] <- "darkred"
pal[9] <- "grey25"
pal[23] <- "turquoise4"
pal[19] <- colors()[60]
pal[13] <- "darkblue"
pal[28] <- colors()[16]
pal[31] <- colors()[54] 
pal <- c(pal,colors()[c(85,84,83,89,45,31,41,42,26,29,10,139,107,108,120,109,119,121,143)])
```

```{r}
indir <- "RDS/"
RDSdir <- "RDS/"
outdir <- "TAM_vs_Oil_V2/"
if (!dir.exists(outdir)) dir.create(outdir)
```

```{r}
load(paste0(indir,"whole_V1p4.Robj"))
```

```{r}
colnames(whole@meta.data)
```

```{r}
DimPlot(whole,group.by = "condition",reduction = "pca")
DimPlot(whole,group.by = "treatment",reduction = "pca")
DimPlot(whole,group.by = "orig.ident",reduction = "pca",shuffle = T)
```
The condition (Tau and non-Tau) is driving most of the variability even if I used harmony over the 4 samples.

To analyze Oil v.s. TAM, I'll need to isolate the specific conditions.

```{r}
PS19 <- subset(whole, subset = condition == "PS19")
WT <- subset(whole, subset = condition == "WT")
```
 
## process PS19 first

```{r}
PS19 <- FindVariableFeatures(object = PS19, selection.method = 'mean.var.plot', mean.cutoff = c(0.0125, 5), dispersion.cutoff = c(0.5, Inf))
#VariableFeatures(whole) <-  VariableFeatures(whole) [!grepl("^Tra|^Trb|^Igh|^Igk|Mamu-a", VariableFeatures(whole))]
#VariableFeaturePlot(whole)

PS19 <- ScaleData(object = PS19, features = VariableFeatures(object = PS19), vars.to.regress = c("nCount_RNA"))
PS19 <- RunPCA(object = PS19,
                features =  VariableFeatures(object = PS19),
                dims = 1:50)
gc()
ElbowPlot(PS19,ndims = 50)

```

```{r}
PS19 <- RunHarmony(object = PS19, group.by.vars = c("orig.ident"), max.iter.harmony = 20) # use harmony to correct for batch effect
PS19 <- RunUMAP(PS19,dims = 1:20,reduction = "harmony") # use harmony embedding for downstream analysis
PS19 <- RunTSNE(PS19,dims = 1:20,reduction = "harmony")

PS19 <- FindNeighbors(PS19, dims = 1:20,reduction = "harmony")
for(res in seq(0.1, 1, 0.1))  {   # iterate over a range of resolutions
  PS19 <- FindClusters(object = PS19, resolution = res, print.output = 0, save.SNN = TRUE)
} 
gc()
PS19 <- JoinLayers(PS19) # required for seurat V5
```

```{r}
DimPlot(PS19, group.by = "treatment",reduction = "pca")
DimPlot(PS19, group.by = "treatment")
DimPlot(PS19, split.by = "treatment")
```

```{r eval=FALSE}
save(PS19,file = paste0(indir,"PS19_V1p4.Robj"))
```


```{r}
cluster_prop <- PS19@meta.data %>% group_by(RNA_snn_res.1,treatment) %>% summarise(size = n()) %>% ungroup() %>%
  group_by(treatment) %>% mutate(percentage = 100*size/sum(size))
```

```{r}
ggplot(cluster_prop)+
  geom_bar(aes(x = treatment,y = percentage, fill = RNA_snn_res.1),stat = "identity", position = "dodge")+
  geom_text(aes(x = treatment,y = percentage,label = size),vjust = 1 ,color = "white",size = 3)+
  facet_wrap(~RNA_snn_res.1,scales = "free")+scale_fill_manual(values = pal[c(1:8,10,13:14,16)])+theme_dark()
```

```{r}
VlnPlot(PS19, split.by = "treatment", features = "Gpnmb")
VlnPlot(PS19, split.by = "treatment", features = "Spp1")
VlnPlot(PS19, split.by = "treatment", features = "Isg15")
VlnPlot(PS19, split.by = "treatment", features = "Ifit3")
VlnPlot(PS19, split.by = "treatment", features = "Axl")
VlnPlot(PS19, split.by = "treatment", features = "Cx3cr1")
```


## process WT first


```{r}
WT <- FindVariableFeatures(object = WT, selection.method = 'mean.var.plot', mean.cutoff = c(0.0125, 5), dispersion.cutoff = c(0.5, Inf))
#VariableFeatures(whole) <-  VariableFeatures(whole) [!grepl("^Tra|^Trb|^Igh|^Igk|Mamu-a", VariableFeatures(whole))]
#VariableFeaturePlot(whole)

WT <- ScaleData(object = WT, features = VariableFeatures(object = WT), vars.to.regress = c("nCount_RNA"))
WT <- RunPCA(object = WT,
                features =  VariableFeatures(object = WT),
                dims = 1:50)
gc()
ElbowPlot(WT,ndims = 50)

```

```{r}
WT <- RunHarmony(object = WT, group.by.vars = c("orig.ident"), max.iter.harmony = 20) # use harmony to correct for batch effect
WT <- RunUMAP(WT,dims = 1:15,reduction = "harmony") # use harmony embedding for downstream analysis
WT <- RunTSNE(WT,dims = 1:15,reduction = "harmony")

WT <- FindNeighbors(WT, dims = 1:15,reduction = "harmony")
for(res in seq(0.1, 1, 0.1))  {   # iterate over a range of resolutions
  WT <- FindClusters(object = WT, resolution = res, print.output = 0, save.SNN = TRUE)
} 
gc()
WT <- JoinLayers(WT) # required for seurat V5
```

```{r}
DimPlot(WT, group.by = "treatment",reduction = "pca")
DimPlot(WT, group.by = "treatment")
```

```{r eval=FALSE}
save(WT,file = paste0(indir,"WT_V1p4.Robj"))
```


