---
title: "glioma subsets"
output: html_document
date: "2024-04-04"
---

```{r}
library(tidyverse)
library(Seurat)
library(harmony)
```

```{r}
rds_in <- "data/"
rds_out <- "data/"
```

```{r}
load(paste0(rds_in,"GBM_RNA_10_glioma_V1.Robj"))
```

# create V1 annotation

```{r}
Glioma <- NormalizeData(Glioma,assay = "RNA", normalization.method = "LogNormalize", scale.factor = 10000)
Glioma <- FindVariableFeatures(object = Glioma, selection.method = 'mean.var.plot', mean.cutoff = c(0.025, 5), dispersion.cutoff = c(0.55, Inf))
#VariableFeatures(Glioma) <-  VariableFeatures(Glioma) [!grepl("^Tra|^Trab|^Igh|^Igk|Mamu-a", VariableFeatures(Glioma))]
VariableFeaturePlot(Glioma,selection.method = "mean.var.plot")

Glioma <- ScaleData(object = Glioma, features = VariableFeatures(object = Glioma), vars.to.regress = c("nCount_RNA", "percent.mt"))
Glioma <- RunPCA(object = Glioma,
                features =  VariableFeatures(object = Glioma),
                dims = 1:50)
gc()

ElbowPlot(Glioma,ndims = 50)
```

```{r}
Glioma <- RunHarmony(object = Glioma, group.by.vars = c("orig.ident"), max.iter.harmony = 20)
Glioma <- RunUMAP(Glioma,dims = 1:30,reduction = "harmony")
Glioma <- RunTSNE(Glioma,dims = 1:30,reduction = "harmony")

Glioma <- FindNeighbors(Glioma, dims = 1:30,reduction = "harmony")
for(res in seq(0.1, 1, 0.1))  {   
  Glioma <- FindClusters(object = Glioma, resolution = res, print.output = 0, save.SNN = TRUE)
} 
gc()
Glioma <- JoinLayers(Glioma)
```


```{r}
DimPlot(Glioma,reduction = "tsne",group.by = "orig.ident",shuffle = T)
DimPlot(Glioma,reduction = "umap",group.by = "orig.ident",shuffle = T)
DimPlot(Glioma,reduction = "umap",group.by = "RNA_snn_res.0.1",label = T,split.by = "progress")
DimPlot(Glioma,reduction = "umap",group.by = "RNA_snn_res.1",label = T,split.by = "progress")
```
```{r}
colnames(Glioma@meta.data)
```


```{r}
Glioma@meta.data <- Glioma@meta.data %>%
  mutate(annotation_V1 =
           case_match(
             as.character(RNA_snn_res.0.1),
             "0" ~ "tumor_1",
             "1" ~ "tumor_2",
             "2" ~ "tumor_3",
             "3" ~ "tumor_4",
             "4" ~ "tumor_5",
             "5" ~ "tumor_6",
             "6" ~ "tumor_7"
           ),
         compartment = rep("neoplastic",nrow(Glioma@meta.data)),
         cell_type = rep("neoplastic",nrow(Glioma@meta.data)),
         annotation_main = rep("neoplastic",nrow(Glioma@meta.data))
         )
```

```{r}
save(Glioma,file = paste0(rds_in,"GBM_RNA_10_glioma_V2.Robj"))
```



