---
title: "check version"
output: html_document
date: "2024-05-06"
---

```{r}
library(tidyverse)
library(Seurat)
library(harmony)
```

# check V1

```{r}
load("data/GBM_RNA_10.Robj")
```

```{r}
DimPlot(whole, reduction = "umap",group.by = "RNA_snn_res.0.1",label = T)
```


```{r failed}
library(SeuratDisk)
SaveH5Seurat(whole, filename = "data/GBM_RNA_10.h5Seurat")

Convert("data/GBM_RNA_10.h5Seurat", dest = "h5ad",overwrite = T)
```

```{r}
whole@meta.data[paste0("SCT_snn_res.",seq(0.1,1.5,0.1))] <- NULL
whole@meta.data[paste0("RNA_snn_res.",seq(1.1,1.5,0.1))] <- NULL
```


```{r}
write.table(whole@meta.data,file = "data/whole_v1_metadata.tsv",sep="\t",col.names = T,row.names = T,quote = F)
```

```{r also don't work for reloading}
library(Matrix)
sparse.whole <- Matrix(GetAssayData(whole,layer = "counts") , sparse = T)
head(sparse.whole)
writeMM(obj = sparse.whole, file="python/matrix.mtx")

# save genes and cells names
write(x = rownames(whole), file = "python/genes.tsv")
write(x = colnames(whole), file = "python/barcodes.tsv")
```

```{r}
DropletUtils::write10xCounts(path="python/data_10x/",GetAssayData(whole,layer = "counts"),barcodes = colnames(whole), gene.symbol = rownames(whole))
```

```{r}
test <- Read10X("python/data_10x/")
```

```{r}
Idents(whole) <- whole$RNA_snn_res.0.1
immune_cells <- subset(whole, idents = c(0,3,4,7,6,10,16,29))
```

```{r}
immune_cells <- NormalizeData(immune_cells,assay = "RNA", normalization.method = "LogNormalize", scale.factor = 10000)
immune_cells <- FindVariableFeatures(object = immune_cells, selection.method = 'mean.var.plot', mean.cutoff = c(0.025, 5), dispersion.cutoff = c(0.55, Inf))
VariableFeatures(immune_cells) <-  VariableFeatures(immune_cells) [!grepl("^Tra|^Trab|^Igh|^Igk|Mamu-a", VariableFeatures(immune_cells))]
VariableFeaturePlot(immune_cells,selection.method = "mean.var.plot")

immune_cells <- ScaleData(object = immune_cells, features = VariableFeatures(object = immune_cells), vars.to.regress = c("nCount_RNA", "percent.mt"))
immune_cells <- RunPCA(object = immune_cells,
                features =  VariableFeatures(object = immune_cells),
                dims = 1:50)
gc()

ElbowPlot(immune_cells,ndims = 50)
```

```{r}
immune_cells <- RunHarmony(object = immune_cells, group.by.vars = c("orig.ident"), max.iter.harmony = 20)
immune_cells <- RunUMAP(immune_cells,dims = 1:30,reduction = "harmony")
immune_cells <- RunTSNE(immune_cells,dims = 1:30,reduction = "harmony")

immune_cells <- FindNeighbors(immune_cells, dims = 1:30,reduction = "harmony")
for(res in seq(0.1, 1, 0.1))  {   
  immune_cells <- FindClusters(object = immune_cells, resolution = res, print.output = 0, save.SNN = TRUE)
} 
gc()
```

```{r}
immune_cells <- JoinLayers(immune_cells)
```

```{r}
DimPlot(immune_cells,reduction = "tsne",group.by = "orig.ident",shuffle = T)
DimPlot(immune_cells,reduction = "umap",group.by = "orig.ident",shuffle = T)
DimPlot(immune_cells,reduction = "umap",group.by = "RNA_snn_res.0.1",label = T)
DimPlot(immune_cells,reduction = "umap",group.by = "RNA_snn_res.1",label = T)
```
```{r}
FeaturePlot(immune_cells,features = "Mpo")
FeaturePlot(immune_cells,features = "S100a8")
FeaturePlot(immune_cells,features = "P2ry12")
FeaturePlot(immune_cells,features = "Lyz2")
FeaturePlot(immune_cells,features = "Adgre1")
FeaturePlot(immune_cells,features = "Flt3")
FeaturePlot(immune_cells,features = "Cd3e")
FeaturePlot(immune_cells,features = "Cd200r3",order = T)
```

```{r}
Idents(immune_cells) <- immune_cells$RNA_snn_res.0.1
neutrophil <- subset(immune_cells,idents = 9)
```

```{r}
save(neutrophil,file = "data/GBM_RNA_10_imm_V1_neutrophil.Robj")
```

# merge neutrophil back to myeloids

```{r}
load("data/GBM_RNA_10_myeloid_V3p1.Robj")
```

```{r}
myeloid <- merge(myeloid,neutrophil)
```

```{r}
myeloid <- NormalizeData(myeloid,assay = "RNA", normalization.method = "LogNormalize", scale.factor = 10000)
myeloid <- FindVariableFeatures(object = myeloid, selection.method = 'mean.var.plot', mean.cutoff = c(0.025, 5), dispersion.cutoff = c(0.55, Inf))

VariableFeaturePlot(myeloid,selection.method = "mean.var.plot")

myeloid <- ScaleData(object = myeloid, features = VariableFeatures(object = myeloid), vars.to.regress = c("nCount_RNA", "percent.mt"))
myeloid <- RunPCA(object = myeloid,
                features =  VariableFeatures(object = myeloid),
                dims = 1:40)
gc()

ElbowPlot(myeloid,ndims = 40)
```


```{r}
myeloid <- RunHarmony(object = myeloid, group.by.vars = c("orig.ident"), max.iter.harmony = 20)
myeloid <- RunUMAP(myeloid,dims = 1:20,reduction = "harmony")
myeloid <- RunTSNE(myeloid,dims = 1:20,reduction = "harmony")

myeloid <- FindNeighbors(myeloid, dims = 1:20,reduction = "harmony")
for(res in seq(0.1, 1, 0.1))  {   
  myeloid <- FindClusters(object = myeloid, resolution = res, print.output = 0, save.SNN = TRUE)
} 
gc()
myeloid <- JoinLayers(myeloid)
```

```{r}
DimPlot(myeloid,group.by = "RNA_snn_res.0.4",label = T)
DotPlot(myeloid,features = c("Ptprc","Cd3e","Cd4","Cd8a","Ncr1","Klrb1c","Gzma","Cd19","Cd79a","Tyrobp","Adgre1","Mertk","Cd44","Ccr2","Siglech","Sirpa","Batf3","Xcr1","Mpo","S100a8","Cd200r3","Lyz2","Sall1","P2ry12","Hexb","Mki67"),group.by = "RNA_snn_res.0.4",cluster.idents = T)+RotatedAxis()
```

```{r}
colnames(myeloid@meta.data)
```
```{r}
myeloid@meta.data[paste0("SCT_snn_res.",seq(0.1,1.5,0.1))] <- NULL
myeloid@meta.data[paste0("RNA_snn_res.",seq(1.1,1.5,0.1))] <- NULL
```

```{r}
myeloid@meta.data <- myeloid@meta.data %>% 
  mutate(annotation_main = case_match(
    as.character(RNA_snn_res.0.4),
    "0" ~ "mono-mac",
    "1" ~ "mono-mac",
    "2" ~ "mono-mac",
    "3" ~ "mono-mac",
    "4" ~ "mono-mac",
    "5" ~ "DC",
    "6" ~ "DC",
    "7" ~ "DC",
    "8" ~ "mono-mac",
    "9" ~ "neutrophil",
    "10" ~ "mast cells"
  ),
  annotation_V1 = case_match(
    as.character(RNA_snn_res.0.4),
    "0" ~ "mono-mac_1",
    "1" ~ "mono-mac_2",
    "2" ~ "mono-mac_3",
    "3" ~ "mono-mac_4",
    "4" ~ "mono-mac_5",
    "5" ~ "cDC1",
    "6" ~ "DC-like",
    "7" ~ "pDC",
    "8" ~ "mono-mac_6",
    "9" ~ "neutrophil",
    "10" ~ "mast cells"
    ),
  cell_type = case_match(
    as.character(RNA_snn_res.0.4),
    "1"  ~ "myeloid",
    .default = "myeloid"
  ))
```

```{r}
table(myeloid$annotation_main)
```

```{r}
table(myeloid$annotation_V1)
```

```{r}
save(myeloid,file = paste0(indir,"GBM_RNA_10_myeloid_V3p2.Robj"))
```

```{r}
FeaturePlot(myeloid,features = "Kit")
FeaturePlot(myeloid,features = "Cd200r3")
FeaturePlot(myeloid,features = "Enpp3")
FeaturePlot(myeloid,features = "Fcer1a")

FeaturePlot(myeloid,features = "Mpo")
FeaturePlot(myeloid,features = "S100a8")
FeaturePlot(myeloid,features = "Itgb2") # CD18
FeaturePlot(myeloid,features = "Itgam")
FeaturePlot(myeloid,features = "Adgre1")
```


