---
title: "Manual Integration"
output: html_document
---



```{r}
library(Seurat)
library(tidyverse)
library(harmony)
```


```{r}
sessionInfo()
```

## process single data

### S0162
```{r}
indir <- "outs/align_outs/"
outdir <- "R_outs_V2/"
sample = "S0162"
obj <- Seurat::Read10X(paste0(indir,"/", sample, "/filtered_feature_bc_matrix"))
```



```{r}
obj = CreateSeuratObject(obj)
obj[["percent.mt"]] = PercentageFeatureSet(object = obj, pattern = "^MT-|^mt-")
obj$nFeature_RNA_log10 = log10(obj$nFeature_RNA)
obj_filtered <- subset(obj, subset = percent.mt < 10 & nFeature_RNA_log10 > 2)
cells.before <- length(colnames(x = obj))
print(cells.before)

cells.after <- length(colnames(x = obj_filtered))
print(cells.after)

```

```{r}
S0162 <- obj_filtered
```

```{r}
sample = "S0163"
obj <- Seurat::Read10X(paste0(indir,"/", sample, "/filtered_feature_bc_matrix"))
obj = CreateSeuratObject(obj)
obj[["percent.mt"]] = PercentageFeatureSet(object = obj, pattern = "^MT-|^mt-")
obj$nFeature_RNA_log10 = log10(obj$nFeature_RNA)
obj_filtered <- subset(obj, subset = percent.mt < 10 & nFeature_RNA_log10 > 2)
cells.before <- length(colnames(x = obj))
print(cells.before)

cells.after <- length(colnames(x = obj_filtered))
print(cells.after)
S0163 <- obj_filtered
```


```{r}
sample = "S0164"
obj <- Seurat::Read10X(paste0(indir,"/", sample, "/filtered_feature_bc_matrix"))
obj = CreateSeuratObject(obj)
obj[["percent.mt"]] = PercentageFeatureSet(object = obj, pattern = "^MT-|^mt-")
obj$nFeature_RNA_log10 = log10(obj$nFeature_RNA)
obj_filtered <- subset(obj, subset = percent.mt < 10 & nFeature_RNA_log10 > 2)
cells.before <- length(colnames(x = obj))
print(cells.before)

cells.after <- length(colnames(x = obj_filtered))
print(cells.after)
S0164 <- obj_filtered
```


```{r}
sample = "S0165"
obj <- Seurat::Read10X(paste0(indir,"/", sample, "/filtered_feature_bc_matrix"))
obj = CreateSeuratObject(obj)
obj[["percent.mt"]] = PercentageFeatureSet(object = obj, pattern = "^MT-|^mt-")
obj$nFeature_RNA_log10 = log10(obj$nFeature_RNA)
obj_filtered <- subset(obj, subset = percent.mt < 10 & nFeature_RNA_log10 > 2)
cells.before <- length(colnames(x = obj))
print(cells.before)

cells.after <- length(colnames(x = obj_filtered))
print(cells.after)
S0165 <- obj_filtered
```

```{r eval=F}
load("/scratch1/fs1/martyomov/carisa/OSU_PR_glioma/R_outs_V2/S0162/S0162_filtered.Robj")

S0162 <- obj_filtered

load("/scratch1/fs1/martyomov/carisa/OSU_PR_glioma/R_outs_V2/S0163/S0163_filtered.Robj")
S0163 <- obj_filtered
  
load("/scratch1/fs1/martyomov/carisa/OSU_PR_glioma/R_outs_V2/S0164/S0164_filtered.Robj")
S0164 <- obj_filtered
load("/scratch1/fs1/martyomov/carisa/OSU_PR_glioma/R_outs_V2/S0165/S0165_filtered.Robj")
S0165 <- obj_filtered
```

## merge and integrate



```{r}
whole <- merge(S0162, y = c(S0163,S0164,S0165),add.cell.ids = c("S0162","S0163","S0164","S0165"))
```

```{r}
rm(S0162)
rm(S0163)
rm(S0164)
rm(S0165)
gc()
```

```{r}
S0162_range = range(grep("S0162",rownames(whole@meta.data)))

whole@meta.data$orig.ident[S0162_range[1]:S0162_range[2]] <- "S0162"

S0163_range = range(grep("S0163",rownames(whole@meta.data)))

whole@meta.data$orig.ident[S0163_range[1]:S0163_range[2]] <- "S0163"

S0164_range = range(grep("S0164",rownames(whole@meta.data)))

whole@meta.data$orig.ident[S0164_range[1]:S0164_range[2]] <- "S0164"

S0165_range = range(grep("S0165",rownames(whole@meta.data)))

whole@meta.data$orig.ident[S0165_range[1]:S0165_range[2]] <- "S0165"
```

```{r}
table(whole@meta.data$orig.ident)
```


```{r}
ggplot(whole@meta.data)+
  geom_histogram(aes(x=percent.mt,y = after_stat(width*density*100)),bins = 100)+
  facet_wrap(vars(orig.ident),ncol=1)+
  geom_vline(xintercept = 10,col="red") +
  ylab("proportion")+
  xlab("percentage of mitochondrial RNA")
```

```{r}
ggplot(whole@meta.data, aes(x = log10(nFeature_RNA))) +
  geom_histogram(bins = 100, aes(y = after_stat(width*density*100))) +
  theme_classic() +
  facet_wrap(~orig.ident, ncol = 1) +
  geom_vline(xintercept = 2,col="red") + 
  geom_vline(xintercept = 4,col="red") + 
  ggtitle("nGene") +
  ylab("")
```

```{r}
whole <- NormalizeData(object = whole, normalization.method = "LogNormalize", scale.factor = 10000)
whole <- FindVariableFeatures(object = whole, selection.method = 'mean.var.plot', mean.cutoff = c(0.0125, 3), dispersion.cutoff = c(0.5, Inf))
whole@assays$RNA@var.features <-  whole@assays$RNA@var.features[!grepl("^TRA|^TRB|^IGH|^IGK|MAMU-A", whole@assays$RNA@var.features)]
whole <- ScaleData(object = whole, features = VariableFeatures(object = whole), vars.to.regress = c("nCount_RNA", "percent.mt"))
```

```{r}
save(whole, file="Manual_Integrated.Robj")
```

```{r}
whole <- RunPCA(object = whole,
                features =  VariableFeatures(object = whole),
                dims = 1:40)
gc()

```

```{r}
ElbowPlot(whole,ndims = 40)

```


```{r}
VariableFeaturePlot(object = whole)
```

```{r}
whole <- RunHarmony(object = whole, group.by.vars = c("orig.ident"), assay.use = "RNA", max.iter.harmony = 20)
whole <- RunUMAP(whole,reduction = "harmony",dims = 1:30)
whole <- RunTSNE(whole,reduction = "harmony",dims = 1:30)
whole <- FindNeighbors(whole, dims = 1:20, reduction = "harmony")
for(res in seq(0.1, 1, 0.2))  {   
  whole <- FindClusters(object = whole, reduction = "harmony", dims = 1:30,
  # resolution = res, print.output = 0, save.SNN = TRUE)
} 
gc()
```

```{r}
save(whole, file="Manual_Integrated.Robj")
```



